### ISSUE TITLE
Add GenotypeGVCFs integration test with GenomicsDB input

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk-protected#1013]
Currently, `GenotypeGVCFs` support for `GenomicsDB` is tested indirectly in public via the generic `GenomicsDBIntegrationTest`, which runs simple test cases on a `VariantWalker`. We should add a direct test in protected for `GenotypeGVCFs` itself as well.

**Comment by droazen** [comment]
For @lbergelson

**Comment by lbergelson** [comment]
Closed by #1018
