### ISSUE TITLE
Use PoN for ACNV, too!

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#102]
The PoN's purpose in ReCapSeg is essentially to make a statistical model for the coverage of each target and to interpret noisy coverage data in a tumor sample in light of this data.

In ACS, each het has its own allelic bias (hence the observed overdispersion) and we currently treat allelic bias of each het as being generated from some global distribution common to all hets.  It would be more powerful to use data from the PoN to learn about the allelic bias *on a het-by-het level*.

**Comment by davidbenjamin** [comment]
Docs for this are in PR #248.  No math other than what is already coded in the allele fraction model is required.

**Comment by davidbenjamin** [comment]
Summarizing some off-line discussions, we're a priori not sure how much allelic bias for a given het differs from sample to sample.  If the inter-sample variability is small, then the simple method described in the docs will be a big win.  If inter-sample variability is large (i.e. if the effect of covariates that vary from sample to sample is important) we would need something more powerful, for example a PCA approach analogous to what we do for coverage.  Fortunately it will be pretty simple to see which actually occurs.

**Comment by samuelklee** [comment]
Closing, as this was addressed by #427.  See also related issues #423 and #435.
