### ISSUE TITLE
gCNV refactoring and code improvement

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#1021]
- [ ] factor I/O methods out of `CoverageModelEMWorkspace` and to a new class
- [ ] shrink the exposed API
- [ ] rename/refactor `CopyRatioCallingMetadata` appropriately
- [ ] rename/move `MathObjectAsserts` to test

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2979](https://github.com/broadinstitute/gatk/issues/2979) via [**ZenHub**](https://www.zenhub.com/)
