### ISSUE TITLE
Automatically calculate AF alleles not present in vcf

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1024]
When M2 tries to get the `AF` from a sites-only resource vcf, it needs to know what `AF` to use for an allele not contained in this vcf.  In principle this should be doable automatically, without requiring an explicit argument.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2980](https://github.com/broadinstitute/gatk/issues/2980) via [**ZenHub**](https://www.zenhub.com/)
