### ISSUE TITLE
Explore -debug output in M2

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1026]
It is worth logging: how often `isActive()` gets triggered and how many haplotypes get assembled.

**Comment by ldgauthier** [comment]
For the haplotype details, the `-debug` argument from AssemblyBasedCallerArgumentCollection will be very helpful.  The docs says it should have active region info too, but I mostly used it for haplotypes.

**Comment by davidbenjamin** [comment]
@takutosato @LeeTL1220 

I wrote a script to mine the debug output for some basic stats.  Here are results from 10Mb of DREAM 4.  We assemble 11000 active regions in order to get just 60 that pass the LoD threshold.  It seems that making `isActive()` smarter is by far a higher priority than reducing the number of haplotypes assembled.

```java
Summary of active region determination and haplotype assembly for running Mutect 2
tumor: /dsde/working/davidben/dream/synthetic/original_bams_symlinks/tumor_4.bam
normal: / /working/davidben/dream/synthetic/original_bams_symlinks/normal_4.bam
interval: 20:10000000-20000000
Number of true variants: 73
Number of calls before filters applied: 63
Number of calls after filters applied: 53
Active regions: 10940
Average number of haplotypes per active region: 3.6649
Times more than 3 haplotypes assembled: 4149
Times more than 5 haplotypes assembled: 1396
Times more than 10 haplotypes assembled: 355
```java

**Comment by davidbenjamin** [comment]
The writing of the aforementioned script and the conclusion that we should focus on reducing the number of active regions fulfills this ticket.
