### ISSUE TITLE
Port gsa-unstable bug fix to increase maximum GQB to 100.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#1029]
Port https://github.com/broadinstitute/gatk-protected/pull/1027.

**Comment by ronlevine** [comment]
@samuelklee Do you mean https://github.com/broadinstitute/gsa-unstable/pull/1451?

**Comment by samuelklee** [comment]
Oops, yup---thanks.

**Comment by ronlevine** [comment]
Created the branch `rhl_max_qdb_value_1451` with the HaplotypeCaller documentation change. Need to wait for https://github.com/broadinstitute/gatk/pull/2682 to be merged in order to grab the gatk public snapshot from the artifactory.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2981](https://github.com/broadinstitute/gatk/issues/2981) via [**ZenHub**](https://www.zenhub.com/)
