### ISSUE TITLE
Make ReadCountCollection error message more informative

### ISSUE THREAD

**Issue by achevali** [broadinstitute/gatk-protected#103]
"the input file cannot be null" will often be due to a PoN and case sample using different bed files. This should be noted in the error.

**Comment by davidbenjamin** [comment]
@achevali where does this occur in the code / does it still exist?

**Comment by samuelklee** [comment]
@achevali is this still an issue?

**Comment by samuelklee** [comment]
Not sure if this is still an issue, closing.
