### ISSUE TITLE
Mutect filter for barcode-swapping duplicates

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1031]
@fleharty has found a common artifact in his UMI work in which barcode swapping causes duplicate reads not to be correctly flagged as such, thereby overestimating the evidence in favor of a false positive variant.  In his examples, several reads usually have the variant at *exactly* the same position.  Less frequently but still often enough that we must deal with it, there will be two sets of artifacts and two distinct positions.

Reasonable approaches to an annotation and corresponding filter include but are not limited to 1) a p-value for this degree of clustering, 2) a simple generative model, and 3) just counting the number of unique positions within the read.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2982](https://github.com/broadinstitute/gatk/issues/2982) via [**ZenHub**](https://www.zenhub.com/)
