### ISSUE TITLE
Prototype siHMM.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#1039]
Hooking up a siHMM (or some variation) to the coverage model from #1038 will be our first cut at GATK CNV 2.0.  Performance and convergence on WGS-size data should be a priority.  The end goal will be a joint siHMM once we also have the 2.0 allele-fraction model prototyped.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2985](https://github.com/broadinstitute/gatk/issues/2985) via [**ZenHub**](https://www.zenhub.com/)
