### ISSUE TITLE
Prototype ADVI coverage model + germline HMM.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#1040]
Following #1038 and in conjunction with #1039.  @asmirnov239, to start, could you make sure you can get the conda environment in https://github.com/broadinstitute/dsde-methods-prototyping/tree/sl_advi up and running?

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2986](https://github.com/broadinstitute/gatk/issues/2986) via [**ZenHub**](https://www.zenhub.com/)
