### ISSUE TITLE
Docker image to use openjdk8

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#1053]
And upgrade ubuntu to 16.04

And leverage the ``broadinstitute/gatk:gatkbase-1.0`` image.  Actually, this will handle the move to OpenJDK8 and ubuntu 16.04.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2990](https://github.com/broadinstitute/gatk/issues/2990) via [**ZenHub**](https://www.zenhub.com/)
