### ISSUE TITLE
Evaluate the necessity for external GC correction vs. depending on the coverage model for ab initio discovery of GC bias

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#1061]
If external GC bias correction was found beneficial, we must do it in the way suggested in the notes, i.e. not directly on the read count table, but as a _hard coded_ bias covariates. This will ensure that the Poisson noise is not under/over-estimated as a result of GC bias correction.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2997](https://github.com/broadinstitute/gatk/issues/2997) via [**ZenHub**](https://www.zenhub.com/)
