### ISSUE TITLE
More flexible integer copy number transition priors in gCNV

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#1062]
- [ ] the ability to _override_ global transition priors in polymorphic regions, etc.
- [ ] the ability to ingest XHMM-like priors (i.e. parametrized models)
- [ ] (bonus) different max copy number states for different genomic loci

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2998](https://github.com/broadinstitute/gatk/issues/2998) via [**ZenHub**](https://www.zenhub.com/)
