### ISSUE TITLE
Limit the number of copy number states and designate a special state to capture all higher copy number states

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#1064]
At the moment, the maximum copy number in gCNV is set by the dimension provided transition matrices. One needs to work with copy number states up to 10 ~ 20 in order to capture high copy number states seen in certain regions.

It is desirable to limit the number of states, however, to designate a special state that represents _all copy number states at and above CN_max_. This can be achieved by adjusting the emission probability to integrate over all higher copy number states. There are other challenges too (e.g. calculating copy number posteriors from such states).

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3001](https://github.com/broadinstitute/gatk/issues/3001) via [**ZenHub**](https://www.zenhub.com/)
