### ISSUE TITLE
Write integration test for GermlineCNVCaller for single sample calling

### ISSUE THREAD

**Issue by asmirnov239** [broadinstitute/gatk-protected#1065]

**Comment by asmirnov239** [comment]
@mbabadi could you do it?

**Comment by sooheelee** [comment]
Is the test <src/test/java/org/broadinstitute/hellbender/tools/coveragemodel/germline/GermlineCNVCallerIntegrationTest.java> not the integration test?

**Comment by asmirnov239** [comment]
@sooheelee  It's a collection of different tests, but it's missing some use cases

**Comment by mbabadi** [comment]
@asmirnov239 it covers PoN creation and calling (from the created PoN, and from the "exact" PoN). It certainly does not cover all combination of all advanced arguments, and we do not intend to do that either. Perhaps we should extend the test to include w/ and w/o ARD, and w/ and w/o bias covariates. I'm open to suggestions.

**Comment by asmirnov239** [comment]
@mbabadi What I meant is to write a single test for a use case of calling events on a single sample (as it is a requirement for our workflows). Just a single test with most generic arguments should suffice I think.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3002](https://github.com/broadinstitute/gatk/issues/3002) via [**ZenHub**](https://www.zenhub.com/)
