### ISSUE TITLE
Instrumentation and ICG function evaluation counts in gCNV

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#1071]
It is desirable to perform an explicit bookkeeping of ICG function evaluation to ensure that gCNV is not performing unnecessary EM evaluation in each cycle.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3007](https://github.com/broadinstitute/gatk/issues/3007) via [**ZenHub**](https://www.zenhub.com/)
