### ISSUE TITLE
TargetCoverageSexGenotyper and PAR regions

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#1085]
- [ ] Add the ability to blacklist PAR regions with an argument, e.g. `--blacklistRegion contig1:start1-end1 --blacklistRegion contig2:start2-end2 --blacklistRegion contig3:start3-end3 ...`

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3008](https://github.com/broadinstitute/gatk/issues/3008) via [**ZenHub**](https://www.zenhub.com/)
