### ISSUE TITLE
Account for base qualities in M2 isActive

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1089]
A large number of spurious active regions are due to non-reference bases with quals less than 10.  The current approach of simply counting non-ref bases is too permissive.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3011](https://github.com/broadinstitute/gatk/issues/3011) via [**ZenHub**](https://www.zenhub.com/)
