### ISSUE TITLE
Count different kinds of alt reads in M2 isActive

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1090]
Currently we lump together all variant reads and add up the total alt evidence.  This classifies too many regions as active.  We should tally reads supporting SNVs (of each possible substitution), deletions, and insertions separately.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3012](https://github.com/broadinstitute/gatk/issues/3012) via [**ZenHub**](https://www.zenhub.com/)
