### ISSUE TITLE
Generative model for orientation bias

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1098]
The telltale sign of a substitution error occurring on a single strand of DNA is that supporting evidence is all on forward strand read 1 and reverse strand read 2, or vice versa.  This lends itself to a graphical model, the hyperparameters of which can be learned from the data.

Further down the road, we might use a neural network to learn the context-specific risk of such artifacts and attach it to the Bayesian model for forward/reverse and read 1/read 2.  This would be our first experience with a deep generative model.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3016](https://github.com/broadinstitute/gatk/issues/3016) via [**ZenHub**](https://www.zenhub.com/)
