### ISSUE TITLE
Approx. date for merging "protected" into "public"?

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk-protected#1104]
First of all, it is great that the Broad Institute add an Open Source license to the protected toolkit. It will be interesting to explore the unlimited possibilities of using some parts of your implementations for other purposes, and I would love to contribute to the protected part too if I detect some bug when running the brand-new GATK4.

Because the current README states that there are plans to merge this repository in the "near future" into the public repository, I wonder if there is any approximate date when this will happen. I wanna explore the protected part soon, but I would like to wait until there is a single artifact for both parts.

Thank you very much in advance.

**Comment by droazen** [comment]
@magicDGS We plan to carry out the merger of the two repositories next week, prior to the beta release on June 2nd.

**Comment by magicDGS** [comment]
Thanks for your quick response, @droazen!

**Comment by lbergelson** [comment]
@magicDGS Expect some chaos during the merger, and please let us know if it inadvertently causes problems for your project.

**Comment by magicDGS** [comment]
Sure @lbergelson. After you merge the two repositories, I will update the dependency to let you know if my tests still pass!
