### ISSUE TITLE
Is it really necessary to "prepare likelihoods for annotation"?

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1112]
In `SomaticGenotypingEngine::callMutations` and `HaplotypeCallerGenotypingEngine::assignGenotypeLikelihoods` there is a line of code after the call is made but before the variant is annotated:
```java
ReadLikelihoods annotationLikelihoods = prepareReadAlleleLikelihoodsForAnnotation(likelihoods...)
```
Is this really necessary?  It seems quite defensible to annotate using the same likelihoods from which the variant call is derived.  As far as Mutect is concerned, the standard will be whether our validations are better or at least no worse without it.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3022](https://github.com/broadinstitute/gatk/issues/3022) via [**ZenHub**](https://www.zenhub.com/)
