### ISSUE TITLE
Use bigger kmers in assembly

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1114]
HaplotypeCaller and Mutect by default assemble reads with kmer sizes of 10 and 25.  10 seems extremely small given the low error rates of Illumina sequencing.  It's worth investigating how the Mutect validations are affected by increasing these values.

**Comment by ldgauthier** [comment]
Investigate away, but keep in mind bigger kmers introduce more "dangling tails", which may end up dropping evidence at the ends of reads.

If you end up diving into the assembly graphs, I'm happy to consult. It's a deep, dark rabbit hole, but I've been there before and I know the way.  ;)

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3024](https://github.com/broadinstitute/gatk/issues/3024) via [**ZenHub**](https://www.zenhub.com/)
