### ISSUE TITLE
Provide mutect equations in pdf format, not just .tex laTex format

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk-protected#1116]
I'm looking at <https://github.com/broadinstitute/gatk-protected/tree/master/docs/mutect>. Can we please provide these in PDF format, much like in the CNV branch of the docs?

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3025](https://github.com/broadinstitute/gatk/issues/3025) via [**ZenHub**](https://www.zenhub.com/)
