### ISSUE TITLE
bed file question

### ISSUE THREAD

**Issue by milkcookie** [broadinstitute/gatk-protected#1135]
Hi：
    Can you tell me how to generate the initial bed file? use the annotation data? or the bed file is just a seperate file for CNV calling? the GATK will detect CNVs from target start to target end? 
Best wishes
FAFU
Hansong Yan

**Comment by cmnbroad** [comment]
@milkcookie This repo is no longer active, as it has been merged into the GATK repo. But the repos are for development related  questions - this kind of questions should be posed to the [GATK forum](https://gatkforums.broadinstitute.org/gatk).
