### ISSUE TITLE
Address comment regarding scripts/generate-test-pcovs-for-create-pon-tool.R 

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#118]
Please see PR #100 comments from @davidbenjamin .

Several R changes were suggested that have not been added to the codebase.  Please see the pull request for more information.  

_Important_: You may have to show outdated diffs in order to see the comments.

`scripts/generate-test-pcovs-for-create-pon-tool.R`

**Comment by samuelklee** [comment]
I think we can probably clean out such scripts (along with python prototypes, test data generation scripts, etc.) at some point.

**Comment by samuelklee** [comment]
This is removed in #1001.
