### ISSUE TITLE
Model GC bias and mappability  explicitly

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#134]
Account for GC (and perhaps mappability), *then* feed the coverage into the PoN.

More ambitiously, replace the PoN with a Bayesian PCA and combine this with known biases in a single graphical model.

**Comment by LeeTL1220** [comment]
Assigning to @achevali , but assuming that @davidbenjamin will be working on it, as well.

**Comment by LeeTL1220** [comment]
Mappability can be optional for beta release.

**Comment by davidbenjamin** [comment]
Closed by PR #532.  Issues for mappability and integrating GC bias in the new coverage model may be created later.
