### ISSUE TITLE
Phasing in ACNV

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#135]
Cancer people want this.  The Sanger has it already.  How would we add this functionality?

**Comment by akiezun** [comment]
I assume you want to not 'do' phasing but 'use' phasing info for better results, a'la HapSeg.

**Comment by davidbenjamin** [comment]
Yes, using, not doing.

**Comment by LeeTL1220** [comment]
We can use Beagle output as input to ANCV

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2825](https://github.com/broadinstitute/gatk/issues/2825) via [**ZenHub**](https://www.zenhub.com/)
