### ISSUE TITLE
(optional) HMM based genotyper

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#147]
This might not be necessary for evaluation as the single sample discovery should be enough for the task.

Basically taking the segments discovered across many case sample we reconsider the genotype for each samples at each of those segments.

**Comment by vruano** [comment]
In fact a simple re-work of the Discover tool would be enough. That tool (still in pull-request stage) goes sample per sample executes Viterbi to get the segments and then genoytypes them on that sample only.

We can change the flow to do instead:

1. Run viterbi across all samples.
2. Sort all the segments (in fact already done in the tool code)
3. Genotype all the input samples and output a joint record across samples (VCF formatted like XHMMs).

So This task could be quite easy once the discovery tool has been merged.

**Comment by davidbenjamin** [comment]
Closed by #414.
