### ISSUE TITLE
QScript for germline CNV calling.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#148]
Once all the components work, we need to glue them together with a Qscript to run the pipeline on real data.

**Comment by davidbenjamin** [comment]
Note that this also includes writing Queue wrappers for all germline command line programs.  @vruano May I self-assign?

**Comment by davidbenjamin** [comment]
PR #48 of the evaluation repo will close this once merged.

**Comment by davidbenjamin** [comment]
Closed in the eval repo.
