### ISSUE TITLE
Revise Qc Metric

### ISSUE THREAD

**Issue by achevali** [broadinstitute/gatk-protected#166]
I know this is the QC that we have always used, but really we should use median consecutive difference divided by standard deviation (or something similar). Otherwise, we would report a wonderful QC improvement if tangent normalization did nothing but rescale the data. Scaling in this way isolates the noise reduction from the scale reduction.

**Comment by achevali** [comment]
Quote from @davidbenjamin

**Comment by samuelklee** [comment]
Some ideas for the new coverage model are underway.
