### ISSUE TITLE
move selected infrastructure pieces to public gatk repo

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk-protected#169]
all parts that are a) mature enough b) shared between germline and somatic CNVs should be moved to the public gatk repo. 

OK to do past alpha.

**Comment by akiezun** [comment]
@LeeTL1220 @vruano can you list here the name of the subcomponents that would be pushed down to gatk public?
A lot of code would qualify I think: Targets, Segments, etc.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2827](https://github.com/broadinstitute/gatk/issues/2827) via [**ZenHub**](https://www.zenhub.com/)
