### ISSUE TITLE
Add support R needs X11/Cairo to be built for plotting

### ISSUE THREAD

**Issue by achevali** [broadinstitute/gatk-protected#185]

**Comment by LeeTL1220** [comment]
@achevali Is this just a simple doc change to make sure cairo and png are supported in a ``capabilities()`` call?

**Comment by samuelklee** [comment]
@achevali can we close this issue?

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2828](https://github.com/broadinstitute/gatk/issues/2828) via [**ZenHub**](https://www.zenhub.com/)
