### ISSUE TITLE
Use `EnumMap` for MCMC parameters

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#195]
`AbstractParametrizedModel` stores a `HashMap<String, Parameter>`, so getters and setters all require hashing a string.  We could save some run time, reduce boilerplate code, and move run-time checks to compile-time by using an `EnumMap` instead, so that `AbstractParametrizedModel` is aware of an `Enum` of its parameters.

**Comment by davidbenjamin** [comment]
For MCMC states with a lot of latent variables that we don't want to record, we could pass an `EnumSet` of parameters that we want to keep samples of to the `GibbsSampler`.

**Comment by davidbenjamin** [comment]
Implementations of `AbstractParameterizedState` wouldn't need getters because they would inherit it from `EnumMap`.

**Comment by samuelklee** [comment]
@davidbenjamin, did you ever try to implement this?  if not, i can give it a go.

**Comment by davidbenjamin** [comment]
@samuelklee I tried briefly but, in my hands at least, the reality was not as pretty as the theory.  For one thing, you have to define a new `Enum` for the parameters of every `AbstractParameterizedState`.  And I seem to recall it was also inelegant whenever the parameters had different types.  I'm not saying it's inevitably undoable, but it's definitely more than a Boy Scout Rule polishing.

**Comment by samuelklee** [comment]
Yeah, I tried a few things earlier today and ran into some issues.  I think having an extensible enum for the parameters of every state is OK, but it's hard (if not impossible) to make those play nicely with EnumMap.  I also found that parameters of mixed type made things difficult.

Could be I'm not the right person for the job either.  Still curious to see if there could be a potential speedup and would be good to get rid of boilerplate if possible, so I'll leave the issue open.

**Comment by samuelklee** [comment]
OK, gave it another try today.  Was able to replace the string keys for each parameter name with enums and use an EnumMap for AbstractParameterizedState.  Looks to give about a 2x speedup for the single-Gaussian and 100-Gaussian models in the unit tests, but the amount of boilerplate is pretty much the same.  Also I think there are still a number of checks that cannot be moved to compile time, unfortunately.  Interested to see how big of a boost the actual copy-ratio and allele-fraction models get---will try to get to this tomorrow!

**Comment by samuelklee** [comment]
Looks like the allele-fraction model is more bottlenecked by all the logGammas it needs to calculate.  Also as @LeeTL1220 we will want to avoid EnumMap for serialization issues.  Still did a lot of refactoring and I think things are a little cleaner, so will issue a PR when I get back!
