### ISSUE TITLE
Reconcile read count and target coverage file formats

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#201]
We have two header formats for target fields:

1.  NAME    CONTIG    START    END
in TargetTableColumns.java.  Used for "read count" files and with TargetTableReader.  Occurs when deriving read counts for PoN creation.

2.  name    contig    start    stop
in TargetCoverageUtils.  Used for "target coverage" files.  Occurs in a lot of downstream tools.

We should choose one, probably #1.  This will require changes to gatk-public.

**Comment by vdauwera** [comment]
I vote for option 1 (mostly because capitals are good in headers for readability)

**Comment by davidbenjamin** [comment]
Closed by PR #447.
