### ISSUE TITLE
Make parameter for cutoff of the eigenvalues (relative to the mean of the eigenvalues) when doing PoN reduction

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#220]
Kaiser's rule would be 0.5
Joliffe's rule would be 0.7

User would specify a flag in `CreatePanelOfNormals`, such as `--reduction-cutoff=0.7`

Default should be 0.7, since we have the most evaluation results for this.

**Comment by davidbenjamin** [comment]
In the new model this is handled with an ARD prior, which has no adjustable parameters.  This issue should be closed for good once we adopt it.

**Comment by davidbenjamin** [comment]
@samuelklee Close?
