### ISSUE TITLE
Integrate the target CR estimate residual model into the DetectCoverageDropout tool

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#221]
Currently, the DetectCoverageDropout tries to use a Gaussian mixture model.  Unfortunately, this has been found to be lacking in its ability to actually model the data.  As part of @kareembroad germline event (issue ??) detection, there will be a model of the residuals (as of this writing).  This model is likely to be better than a GMM and we should use that instead.

**Comment by samuelklee** [comment]
@LeeTL1220 are we still going to do this?

**Comment by samuelklee** [comment]
@LeeTL1220 should I keep this open?  Where is DetectCoverageDropout being used?

**Comment by samuelklee** [comment]
Closing, DetectCoverageDropout is not in use.
