### ISSUE TITLE
EGFR event detection in LUAD

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#222]
In the TCGA LUAD data, there are several samples (~25) with EGFR event.  Additionally, some of these events are a subset of the exons (numbers 2-7?), since this is a common cancer mutation.  

This issue is to evaluate our sensitivity to detect these EGFR mutations, since these are clinically relevant.  

GISTIC results (on arrays) can tell us which LUAD samples have these mutations.  However, these results will not tell us if only a subset of the gene is mutated.  That will have to be curated manually.

Originally recapseg repo issue number 340

**Comment by samuelklee** [comment]
Closing this as other evaluations will be easier to implement and are higher priority.
