### ISSUE TITLE
PoN target filtering is likely too aggressive, can we be more intelligent about it?

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#223]
We lose a lot of targets to our filtering (>20%).  This seems a bit high, especially after @achevali analysis of the actual std in each of the targets.  We could probably cut fewer targets without any hit to our results.

See recapseg issue number 53 for the plots.

https://github.com/broadinstitute/recapseg/issues/53

**Comment by samuelklee** [comment]
@mbabadi something to look at for the new PoN.  Even if filtering extreme targets is no longer necessary, we may want to think about how to filter common germline CNV, etc.
