### ISSUE TITLE
Plot ACNV segments in separate plots

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#224]
For each segment, create a plot similar to that of the CGA AllelicCapSeg.  We do not need all of the plots.  Just the ones that show the CR and the MAF (I believe those are on the left in AllelicCapSeg).  

I believe it does two segments per plot, though you would have more details, @achevali 

@achevali Can you post an example here?

**Comment by LeeTL1220** [comment]
@achevali I changed this issue to the segment-level plotting.

**Comment by samuelklee** [comment]
We also discussed possibly having some interactive plots in the future.  I think that checking out packages like plotly (https://plot.ly/r/) would be a good start, with the ultimate aim of building some sort of shiny dashboard (http://shiny.rstudio.com/) that takes in seg files from CNV/ACNV/etc. and generates several plots at once.  Even simple things like being able to interactively select which chromosomes/segments to plot, having the ability to zoom, or hover-highlighting segments would make the results much easier to parse and interpret.

**Comment by akiezun** [comment]
I recommend D3 for interactive plots:
https://github.com/mbostock/d3/wiki/Gallery

**Comment by vdauwera** [comment]
D3 is pretty sweet. 

Generally speaking interactive plots are a very attractive prospect -- all thumbs up from my end.

**Comment by LeeTL1220** [comment]
For interactive plots, I created a new issue for a future milestone.  I do not want to attempt interactive plots for this milestone/Q2 goals.
