### ISSUE TITLE
Separate male and female PoNs

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#229]
This would allow us to do copy number analysis on X and Y chromosomes.  Currently, this is only supported by having the user create two separate PoNs for male and female and then determining which PoN to use for each case sample.

Details of implementation must also be fleshed out, since this is a conceptually simple issue, but needs to be as easy as possible for the user.

**Comment by davidbenjamin** [comment]
@mbabadi's masking matrix enhancement to the new coverage model will handle this very cleanly.  Close this issue once it is adopted.

**Comment by samuelklee** [comment]
Essentially a duplicate of #526.
