### ISSUE TITLE
Reduce time to run ``CombineReadCounts`` (with Spark)

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#231]
This step is rapidly becoming the bottleneck for PoN creation (>15 minutes for the standard Broad CGA Agilent PoN).  Can we use Spark to write out this TSV?

**Comment by samuelklee** [comment]
This step is not really necessary, since we should be able to pass the coverage files separately without aggregating.  Although it is still used in gCNV, I think we should aim to remove it.  @mbabadi @asmirnov239
