### ISSUE TITLE
Test failing due to wrong test file path

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#234]
Test are failing locally for me for the PadTargetsIntegrationTest. The "targets.bed" file directory is wrong... it should be .../broadinstitute/hellbender/tools/exome/targets.bed but currently the "hellbender" subdirectory is omitted. Please don't add an additional targets.bed file, just use the one in existence (I am assuming that the content would be the same).

**Comment by davidbenjamin** [comment]
@vruano Fixed in the ACS Model pull request that was just merged a minute ago.

**Comment by vruano** [comment]
Cool thanks.
