### ISSUE TITLE
Compilation warnings coming from AlleleFractionState.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#237]
Not a tragedy but annoying:
<pre>
/Users/valentin/Developer/hellbender-protected/src/main/java/org/broadinstitute/hellbender/tools/exome/allelefraction/AlleleFractionState.java:25: warning: [rawtypes] found raw type: List
        public MinorFractions(final List other) {
                                    ^
  missing type arguments for generic class List<E>
  where E is a type-variable:
    E extends Object declared in interface List
/Users/valentin/Developer/hellbender-protected/src/main/java/org/broadinstitute/hellbender/tools/exome/allelefraction/AlleleFractionState.java:26: warning: [unchecked] unchecked method invocation: constructor <init> in class ArrayList is applied to given types
            super(new ArrayList<>(other));
                  ^
  required: Collection<? extends E>
  found: List
  where E is a type-variable:
    E extends Object declared in class ArrayList
/Users/valentin/Developer/hellbender-protected/src/main/java/org/broadinstitute/hellbender/tools/exome/allelefraction/AlleleFractionState.java:26: warning: [unchecked] unchecked conversion
            super(new ArrayList<>(other));
                                  ^
  required: Collection<? extends E>
  found:    List
  where E is a type-variable:
    E extends Object declared in class ArrayList
/Users/valentin/Developer/hellbender-protected/src/main/java/org/broadinstitute/hellbender/tools/exome/allelefraction/AlleleFractionState.java:26: warning: [unchecked] unchecked method invocation: constructor <init> in class ArrayList is applied to given types
            super(new ArrayList<>(other));
                 ^
  required: Collection<? extends E>
  found: ArrayList
  where E is a type-variable:
    E extends Object declared in class ArrayList
/Users/valentin/Developer/hellbender-protected/src/main/java/org/broadinstitute/hellbender/tools/exome/allelefraction/AlleleFractionState.java:26: warning: [unchecked] unchecked conversion
            super(new ArrayList<>(other));
</pre>

**Comment by vruano** [comment]
```git blame```s you @davidbenjamin

**Comment by akiezun** [comment]
i think you guys should run the compiler with `'-Werror'` and eliminate all warnings

**Comment by vruano** [comment]
Does is what is done in gatk (public)?

**Comment by akiezun** [comment]
yes

**Comment by vruano** [comment]
Sounds good, will take care.

**Comment by vruano** [comment]
Why you do '-proc:none'?

**Comment by samuelklee** [comment]
this will be fixed up in my sl_alleliccapsegger branch.

**Comment by vruano** [comment]
I have already a pull-request on it ready to be merged. Very simple. @samuelklee wanna review it?

**Comment by samuelklee** [comment]
Closed by #238
