### ISSUE TITLE
Change chromosome order of HetPulldown and ACS segfiles.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#243]
Currently in lexicographical order, should change to natural order.

**Comment by vruano** [comment]
What you mean with natural order? same as the reference file? What is it important?

**Comment by samuelklee** [comment]
just to be consistent with the segfiles output by CBS (which are in the order 1, 2, 3... rather than 1, 10, 11...).  not a critical issue, but maybe @LeeTL1220 can comment further.

**Comment by vruano** [comment]
In the past I had discussions about this with @droazen, @lbergelson and for what I remember would should tray to make our programs non-dependable on a particular chromosomal order thus making depend on the presence of the reference file. 

Even if HetPulldown may already require the reference to be around for any other reason as a matter of principle we would avoid any coding in tools that is there just for the sake of honoring the reference order. 

If you need that in order for the sake of comparing results with CBS, I reckon this is only needed for doing some evaluation now and is not a desired permanent feature. In that case you can rearrange the output appropriately with an external custom script; you might well need to hack an script for the comparison anyway.

Perhaps @droazen and @lbergelson can weight in.

**Comment by samuelklee** [comment]
i see.  note that nothing critical depends on the chromosome order, it's just a matter of having consistent output---i think that the segfiles from CBS (i.e., GATK CNV) and GATK ACS should have the same order.

if CBS is the only thing using natural order in its output, perhaps we should just change it there (which is just a matter of changing one line in the R script, i believe).  @achevali might also have an opinion.
