### ISSUE TITLE
Fix segment-union step.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#244]
Currently strands hets/targets due to fencepost errors, leading to oversegmentation downstream.  Parsimonious interval should also be refactored to be based on target ends.

**Comment by samuelklee** [comment]
Some working notes.  @davidbenjamin and @LeeTL1220 might want to comment.

1) Fencepost errors were occurring when a new segment was being created from e.g. a target-segment start breakpoint and a SNP-segment start breakpoint.  The single SNP at the start of the SNP segment was being included in the new segment, leading to difficulties in similar-segment merging downstream.  I think that this problem is solved by keeping track of the type of each breakpoint (i.e., start or end), and decreasing the end of the new segment by one if the corresponding breakpoint was originally a start.

2) Naive unioning of breakpoints is introducing new segments that contain only targets (e.g., when two SNP segments occur within a single target segment, 3 such segments at the start, middle, and end are created).  If the target coverages in these new segments are all high or low by chance, these spurious segments may not get remerged during similar-segment merging, even if the merge threshold is quite aggressive (e.g., 5 sigma).

I think an easy solution is to check all new segments containing only targets against the original CBS target segments, and discard those that were not preexisting.  This can be done in small-segment merging.

3) Making the unioned segments parsimonious (i.e., making sure that their endpoints corresponding to target starts/ends or SNP sites) is also problematic.  For example, if a SNP-segment breakpoint breaks up a target segment into two new segments but also happens to fall *within* a target, which of the two segments should that target belong to?  Right now, I believe that the end of the first new segment is extended to the end of that target, but this is problematic when the next breakpoint also falls within that target.

Note that the output of GATK CNV defines target segments by the target ends, so perhaps we should follow this convention here as well.

**Comment by samuelklee** [comment]
Another thought: rather than just merging the "middle" segments described above, model comparison over all possible breakpoints contained within them could be performed.

**Comment by davidbenjamin** [comment]
Fixed in PR #254.
