### ISSUE TITLE
Get target file for coverage (and other case sample workflow steps) from the PoN

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#249]
We could save some time on coverage collection by using a target file generated from the PoN.

Currently, the same target file for the PoN must be used for the case sample.  This has caused issues:
- out of sync.  The user uses a different target file for the case samples than for the PoN
- calculating coverage for targets that will not be used.  Many targets are filtered out in the PoN.  Why calculate the coverage for these?

**Comment by samuelklee** [comment]
No longer necessary with the new coverage model.
