### ISSUE TITLE
Output other ACNV model parameters to file.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#251]
Right now we are just outputting posterior summaries for copy ratio and minor allele fraction.  Output of posterior summaries for the other global parameters (outlier probability, ref bias, etc.) should be added at some point..

**Comment by davidbenjamin** [comment]
Agreed!

**Comment by LeeTL1220** [comment]
@samuelklee Is this already done?  Can we close this issue?

**Comment by samuelklee** [comment]
Not done yet.  We can chat today about what should go into this file, but if these model parameters aren't directly used downstream I'd say this issue is lower priority.

**Comment by LeeTL1220** [comment]
Lowering priority...

**Comment by samuelklee** [comment]
Raising priority again after our discussion with Grace on CNLOH.  See also #527.
