### ISSUE TITLE
Remove uses of RCS, ACS, etc.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#253]
Lots of uses of "ReCapSeg", "RCS", "AllelicCapSeg", "ACS", etc. are still floating around.  Update these after we finalize tool names.

**Comment by LeeTL1220** [comment]
I am not sure how best to modify the docs.  Filing another issue for the ``docs/`` dir

**Comment by LeeTL1220** [comment]
Issue #303 filed
