### ISSUE TITLE
Change AllelicCount::toMinorAlleleFraction

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#258]
Currently we use`min(a,r)/(a+r)` where a and r are the alt and ref read counts.  However, this is biased.  For example, if MAF = 1/2 and there are `n` total reads, then `a - n/2` is distributed (if `n` if big enough for the central limit theorem to be reasonable i.e. n > 20 or so) as N(0, n/4) and thus `min(a,r)` follows a half-normal distribution and has mean sqrt(n/(2pi)).  Thus the mean MAF estimate is 1/2 - 1/sqrt(2 pi n).  For `n=30` this error term 1/sqrt(2 pi n) is 0.073.  This could be enough to oversegment the allelic data.

A less-biased (and computationally more expensive but it only has to be computed once) estimate comes from the following probabilistic calculation:  Ignoring bias, the likelihood is proportional to f^a * (1-f)^r + f^r * (1-f)^a -- the sum arises from the fact that a priori alt minor and ref minor are equally likely.  We integrate this from f = 0 to 1/2 to get the normalization constant of this distribution (the posterior equals the likelihood if we assume a flat prior on the MAF f), and we multiply by f and integrate to get numerator of the mean MAF (the denominator being the normalizing constant).  Thus we get:

mean MAF = [I(1/2, a + 2, r + 1) + I(1/2, r + 2, a + 1)] / [I(1/2, a + 1, r + 1) + I(1/2, r + 1, a + 1)]

where I is the incomplete beta function, which is in Apache Commons.

**Comment by samuelklee** [comment]
this sounds good to me!

**Comment by davidbenjamin** [comment]
Closes by PR #326.
