### ISSUE TITLE
Overhaul README to shorten it dramatically

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#262]
User information should be in the forum.  In general, a user should not have to go to the github repo for any information.

Our README is too long and should be broken into smaller pieces and posted in the forum.  

Link from @vdauwera :
``http://gatkforums.broadinstitute.org/categories/gatk-4-alpha``

**Comment by samuelklee** [comment]
note that install_R_packages.R has been updated slightly:

    source("http://bioconductor.org/biocLite.R")
    biocLite("DNAcopy")
    #Make sure to use http not https as this will give an "unsupported URL scheme" error
    getoptUrl="http://cran.r-project.org/src/contrib/getopt_1.20.0.tar.gz"
    if (!("getopt" %in% rownames(installed.packages()))) {
      install.packages(getoptUrl, repos=NULL, type="source")
    }
    optparseUrl="http://cran.r-project.org/src/contrib/optparse_1.3.2.tar.gz"
    if (!("optparse" %in% rownames(installed.packages()))) {
     install.packages(optparseUrl, repos=NULL, type="source")
    }
    dependencies = c("naturalsort")
    if (!all(dependencies %in% rownames(installed.packages()))) {
      install.packages(setdiff(dependencies, rownames(installed.packages())), repos="http://cran.cnr.Berkeley.edu")
    }
    q(save="no")
