### ISSUE TITLE
Find a better way for determining the number of partitions/slices to use for Spark

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#276]
Particularly in the SVD spark calculations.  This is hardcoded to 50, which could cause issues later.

What is the best general strategy?

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2831](https://github.com/broadinstitute/gatk/issues/2831) via [**ZenHub**](https://www.zenhub.com/)
