### ISSUE TITLE
Do we still want these methods (e.g. betathats, tangentNormalization) attached to the PoN interface?

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#278]
In PoN.java...

Most operations on a PoN are in the TangentNormalizer class.  The PoN class is mostly used to store data, not perform operations.

Should we refactor these methods into TangentNormalizer?

**Comment by davidbenjamin** [comment]
@LeeTL1220 Yes.  But IMO we should also refactor betahats entirely out of existence or at least make it private.  All it does is calculate coefficients to project onto the (reduced) PoN, and it doesn't make sense to expose an intermediate step of the normalization.

**Comment by LeeTL1220** [comment]
@davidbenjamin In the spark tangent normalization, it basically is an intermediate calculation that is only kept because the existing infrastructure expects it.

**Comment by samuelklee** [comment]
Refactored in #618.  `CoveragePanelOfNormals` interface now only has a single `normalize` method.
