### ISSUE TITLE
Support blacklisting regions for WGS

### ISSUE THREAD

**Issue by achevali** [broadinstitute/gatk-protected#287]
Such as common germline cnv

**Comment by LeeTL1220** [comment]
Given that we have a flag for pruning X, Y, and M/MT, I am putting the arbitrary blacklist for WGS to a later milestone.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2832](https://github.com/broadinstitute/gatk/issues/2832) via [**ZenHub**](https://www.zenhub.com/)
