### ISSUE TITLE
Target and Sample Filter tool.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#296]
Tool to filter targets and samples based in several thresholds.

This tool will generate two main files one that indicate the targets that are not filtered 
and another the samples that are not filtered. 

Each threshold will have its own user argument

```
   -maxSampleMean DBL --maximumSampleMean DBL     (short and full names; suggestions accepted.)
   -minSampleMean DBL --minimumSampleMean DBL
   -maxSampleStdDev DBL --maximumSampleStdDev DBL
   -minSampleStdDev DBL --minimumSampleStdDev DBL
   -maxTargetGCContent DBL --maximumTargetGCContent DBL
   -minTargetGCContent DBL --minimumTargetGCContent DBL
   -minTargetSize INT --minimumTargetSize INT
   -maxTargetMean DBL --maximumTargetMean DBL
   -minTargetMean DBL --minimumTargetMean DBL
   -maxTargetRepeatContent DBL --maximumTargetRepeatContent DBL
```
Seems lots of filters but they are quite simple to implement.

## Input 

In order to do this, this filter tool (which could be call ```FilterSamplesAndTargets```), would take in the products of the ```AnnotateTargets``` tool (currently the GC, repeat content), and the ```CalculateCoverageStats``` to decide what is left in or left out. 

## Filtering order:

Self contained filters (those whose outcome does not depend on any other filter) are applied first:
  target size, gc and repeat content.

After that we apply the sample filters, and then the remaining target filters; so the latter won't take in 
consideration samples filtered by the former.

## Output:

The sample kept file should be a simple text file where each sample names is in a line. Preferably sorted alphabetically. 

```
   NAME
   SAMPLE_1
   SAMPLE_2
   SAMPLE_5
   ...
```

The target kept file is a standard target table file where 
```
   CONTIG   START   END  NAME 
   1               33131     33151  TARGET_1
   1               33231     33267  TARGET_3
```

In addition it should also generate a couple of rejects file indicate the filtered out targets and samples and the reason why they are filtered.

For now this file can have whatever format is more convenient although we should aim to make it quite nice to read and parse in the future. 

E.g.

```
    NAME            FILTER                                DETAILS
    SAMPLE_3    AverageCoverageMax   The sample coverage (123.12) is greater than the maximum (100.00)
    SAMPLE_3    StdDevCoverageMax     The sample coverage std.dev. (73.12) is greather than the maximum (50.00)

**Comment by davidbenjamin** [comment]
Closed by PRs #323 and #339.
