### ISSUE TITLE
Evaluation using LMM data.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#297]

**Comment by davidbenjamin** [comment]
Waiting on more samples from LMM.  Current results with 8 samples are uninformative.

**Comment by davidbenjamin** [comment]
With 38 samples, 8 of which have truth data we find 6 out of 8 confirmed CNVs.  When applying a simple post-calling filter of rejecting segments on which both duplications and deletions are called (evidence of tangent normalization failing) there is only 1 false positive.  I strongly suspect that issue #375 (testing in progress) or issue #378 will eliminate false positives in a more principled way.

**Comment by davidbenjamin** [comment]
Done with original germline model; issue #541 is for new model.
