### ISSUE TITLE
Use ``treeAggregate`` (or similar) rather than ``countByValue`` in ``SparkGenomeReadCounts``

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#306]
countByValue aggregates all of the computation to a single node.  treeAggregate will do intermediate calculations on the partitions and minimize the burden on the final node.  When @akiezun ran `SparkGenomeReadCounts` it overloaded the driver in spark.  This should fix that.

**Comment by LeeTL1220** [comment]
Performance looks good enough that we probably do not have to address this anytime soon.

**Comment by samuelklee** [comment]
Closing, although perhaps @asmirnov239 should consider this in his rewrite of the coverage collection if it is relevant.
