### ISSUE TITLE
Make SimpleInterval key into an Integer key

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#309]
SimpleInterval serializes into more bytes than Integer.  For WGS, this may affect the performance when running on Spark.  We should convert SimpleIntervals into Integers.  Possibly by using global genomic coordinates for the given reference.  We should implement conversion in both directions:  SimpleInterval <--> Integer (global genomic corrds)

**Comment by LeeTL1220** [comment]
Performance looks good enough that we probably do not need to address this anytime soon.

**Comment by samuelklee** [comment]
Closing since relevant WGS performance seems adequate.
