### ISSUE TITLE
Make sure that ``CreatePanelOfNormals`` can be run on spark cluster

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#316]
How does the performance look?
This may also include having to troubleshoot adding a `sparkJar` artifact to `build.gradle`.

**Comment by LeeTL1220** [comment]
Dependent on issue #317

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2834](https://github.com/broadinstitute/gatk/issues/2834) via [**ZenHub**](https://www.zenhub.com/)
