### ISSUE TITLE
Include flag to prevent CBS from creating segments that span large distances between adjacent targets.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#335]
This issue apparently arises when running on gene-panel data.  One easy (if slightly hacky) fix would be to introduce artificial chromosome breakpoints between all targets > Xkb apart (where X can be a command-line parameter); CBS will not merge across chromosomes.  This can be done in the CBS R script.  @achevali, this might be up your alley?

**Comment by LeeTL1220** [comment]
We are currently discussing a new segmentation scheme, which would obviate the need for this hack.

Moving to later milestone and warning anyone following this issue that we may not implement it.
