### ISSUE TITLE
Split Segment Calling Evaluation

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#338]
- [ ] Replicate matlab prototype results using the Java code for the split segment calling only.
- [x] Use data from Amaro to evaluate

**Comment by LeeTL1220** [comment]
GT results from Amaro (Broad internal only):

```
Here are the CLL files:

/xchip/cga_home/amaro/CLL/ABSOLUTE/SCNA_CCF_recall_5.17/

The headers are as follows:

Chromosome	Start_bp	End_bp	n_probes	length	n_hets	f	tau	sigma_tau	mu_minor	sigma_minor	mu_major	sigma_major	SegLabelCNLOH	sample	NA	NB	chisq	CCF_hat	CCF_Low	CCF_High	muA_fit	muB_fit	tau_fit	NA_nextbest	NB_nextbest	chisq_nextbest	CCF_hat_nextbest	muA_nextbest	muB_nextbest	tau_nextbest	purity	ploidy	IS_SCNA	CCF_Low_nextbest	CCF_High_nextbest



Chrom
Start
End
n_probes
length
n_hets
f < -- minor allele fraction
tau <-- non-log2 copy ratio direct from recapseg
sigma_tau <-- direct from recapseg error on tau
mu_minor <--- f * tau 
sigma_minor <--- error on allele copy ratio derived from the 95% CI on the joint binomial dist of hets on the minor allele
mu_major <-- (1-f)*tau
sigma_major <-- same as minor
---------------------------------------------------------------------------- Our SCNA CCF columns
NA copy number minor
NB copy number major
CCF_hat just ccf
CCF_low and high are the CIs
and the rest are the second best fit. 

```

**Comment by LeeTL1220** [comment]
``CLL_Wu_workspace`` for the bam files

**Comment by LeeTL1220** [comment]
This is getting moved to a later milestone.  

Manual curation of prototype results showed that the ground truth was not always correct.  Going to implement and pass to CGA.  Two members of CGA offered to show us any poor performance, which alleviates any urgency here.

**Comment by LeeTL1220** [comment]
Suggestion from Amaro that there are a lot of CNLoH in testicular (TGCT) data.

**Comment by LeeTL1220** [comment]
Going to compare against recapseg + ACS +  ABSOLUTE results prepared in Firehose.

Workspace: ``GCT_Clinical_Master_Workspace``

ABS annotation: ``absolute_seg_file``

**Comment by LeeTL1220** [comment]
Modifying this issue to encompass only the split segment evaluation.  We will mark CNLoH as experimental, since preliminary results indicate issues with hi/low ploidy in the tumor sample

**Comment by LeeTL1220** [comment]
Waiting on feedback from CGA....

**Comment by samuelklee** [comment]
Closing, not relevant as I gave CGA a script to do ACS-style split calling.  Will file new issues based on feedback (if any).
