### ISSUE TITLE
Allow ACNV to output an allelic seg file that mimics the legacy format of AllelicCapSeg

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#346]
Allelic CapSeg format:
```
Chromosome | Start.bp | End.bp | n_probes | length | n_hets | f | tau | sigma.tau | mu.minor | sigma.minor | mu.major | sigma.major | SegLabelCNLOH	
---------- | -------- | ------ | -------- | ------ | ------ | - | --- | --------- | -------- | ----------- | -------- | ----------- | -------------
1 | 2500 | 124997500 | 24999 | 124995000 | 5000 | 0.5 | 2 | 4e-05 | 1 | 0.02 | 1 | 0.02 | 2	
```

ACNV format:
```
Sample  Chromosome      Start   End     Num_Targets     Num_SNPs        Segment_Mean_Post_Mode  Segment_Mean_Post_Lo    Segment_Mean_Post_Hi    MAF_Post_Mode   MAF_Post_Lo     MAF_Post_Hi

```

**Comment by LeeTL1220** [comment]
``length`` is just ``End - Start``

Decision still needed for how to represent the *.sigma fields.

**Comment by dlivitz** [comment]
Small note: 
MAF_Post_Mode is confusing because it could mean Minor Allele Fraction or Major Allele Fraction

**Comment by samuelklee** [comment]
Thanks for the feedback, @dlivitz.  MAF_Post_Mode should always be below 0.5, but there's certainly no harm in making the column names more verbose.  Also, *_Lo and *_Hi currently give the 95% highest-posterior-density credible-interval bounds, so those could probably be renamed as well.  Suggestions welcome!

The issue with translating to sigmas is more dicey---our models are different from those of ACS.  But perhaps something can be done with the credible-interval bounds.
