### ISSUE TITLE
CombineReadCounts fails when targets' chromosome order is 1, 2 . . . 23

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#353]
`HashedListTargetCollection` is traversed in the lexicographical order of contigs because its `sortedIntervals` field is initialized via `IntervalUtils.LEXICOGRAPHICAL_ORDER_COMPARATOR`.  This is the order that `CombineReadCounts` uses when it calls `targets.targets()`.  Therefore, if the targets are in the order 1, 2, 3 . . . 23, it goes through chromosome 1, then does `seekTarget` to chromosomes 11, 12, 13, 14 . . . 19.  Next `seekTarget` looks for the first target in chromosome 2, which fails because it jumped past 2, 3, 4 . . . 9 in order to reach chromosome 11 after chromosome 1.

To reproduce this error quickly, run `CombineReadCountsIntegrationTest` but replace `TEST_CHR = new String[] { "1", "2", "3"}` with `TEST_CHR = new String[] { "1", "2", "11"}`.  Note also that it passes for {"1", "11", "2"}.

The root of the issue is that there are two inconsistent target orderings, the lexicographically sorted order of `HashedListTargetCollection` and the order of the original targets file.

**Comment by samuelklee** [comment]
note some related discussion in #243.
