### ISSUE TITLE
Het Pulldown in acnv finds sites on nonhomolgous Y

### ISSUE THREAD

**Issue by dlivitz** [broadinstitute/gatk-protected#355]
I've been running acnv in firecloud on the colocated tcga bams. 

I noticed it called some hetsites on Y - I included the path to my run below. 

I know an easy fix would be to remove the Y chromosome, but I'm worried that other noisy sites are included. 

Let me know if more information will be helpful! 

all run files (what cromwell copied out): 
/xchip/cga_home/dlivitz/dropbox/acnv_y_hets/
normal hets: 
/xchip/cga_home/dlivitz/dropbox/acnv_y_hets/TCGA-GC-A4ZW-01A-11D_TCGA-GC-A4ZW-10A-01D.normal.hets.tsv

**Comment by LeeTL1220** [comment]
@samuelklee @davidbenjamin I'm not sure whether we should be worried about this.  If we want to address this, then this issue should be re-labeled as a bug.  Can we decide tomorrow (Feb 10, 2016)?

**Comment by LeeTL1220** [comment]
```
$ egrep "^Y" /xchip/cga_home/dlivitz/dropbox/acnv_y_hets/TCGA-GC-A4ZW-01A-11D_TCGA-GC-A4ZW-10A-01D.normal.hets.tsv
Y       13496371        28      20
Y       13500604        29      25
Y       13500769        14      5
Y       13524507        13      12
Y       13524664        23      23
Y       13524719        10      3


```

**Comment by samuelklee** [comment]
These don't directly affect the ACNV results because X and Y are dropped (as a result of being dropped by CNV).  Whether or not we want such sites to be emitted by HetPulldown is a separate issue.  As for whether such "noisy" sites are being emitted elsewhere, I'd first want to understand where these reads are coming from...I'll look into it tomorrow!

**Comment by akiezun** [comment]
Did you exclude the PAR ?
https://en.m.wikipedia.org/wiki/Pseudoautosomal_region

On Tuesday, February 9, 2016, samuelklee <notifications@github.com> wrote:

> These don't directly affect the ACNV results because X and Y are dropped
> (as a result of being dropped by CNV). Whether or not we want such sites to
> be emitted by HetPulldown is a separate issue. As for whether such "noisy"
> sites are being emitted elsewhere, I'd first want to understand where these
> reads are coming from...I'll look into it tomorrow!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gatk-protected/issues/355#issuecomment-182185148>
> .
>


-- 
Sent from Gmail Mobile

**Comment by LeeTL1220** [comment]
We are going to address this.

**Comment by samuelklee** [comment]
Adding basic mapping/base quality filters removes many of these sites without adversely affecting ACNV concordance with HAPSEG by removing too many hets elsewhere.  So we've addressed the possibility that "noisy" sites might be affecting the ACNV results.

However, some sites on Y still remain and are supported by many reads with mapping quality >30-40 in several samples.  So we may want to explicitly blacklist non-PAR sites in the output of HetPulldown (and should probably also remove them from the list of common SNPs used), but I will move this to beta for now.

**Comment by samuelklee** [comment]
As discussed in #518, we'll simply omit chromosomes X, Y, and etc. from the list of common SNPs (to be consistent with how this is handled on the coverage side).
