### ISSUE TITLE
Advanced MAF == 0.5 caller in ACS output

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#359]
This issue is to implement a method to peg MAF at 0.5 in the output of ACNV, if there is sufficient evidence.  This could be done several ways, including model comparison against a model of 0.5.  Additionally, this should consider SNP-specific models in the model estimates.

**Comment by davidbenjamin** [comment]
The CN-LOH caller I'm working on does this, at least on paper.

**Comment by LeeTL1220** [comment]
This is happening as part of #338 and #225
