### ISSUE TITLE
Utility to determine if a case sample is a good fit for a particular PoN

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#360]
@dlivitz, @danielrosebrock, and @iglc used a PCA on an approximation of the *diff* of the coverage profiles in a PoN (``fnt_control_matrix``)

This allowed clustering of the samples in the PoN.

This issue covers the implementation of a tool that will perform the transformation into PoN PCA space of a case sample.  We can then estimate whether the case sample falls into a cluster or not.  This would give us an approximation of the "fit" between a PoN and a case sample.

Thanks to the excellent work of @dlivitz, @danielrosebrock, and @iglc

**Comment by davidbenjamin** [comment]
Issue #430 will include this naturally.  "Position in PCA space" is the E step of the generative coverage model.
