### ISSUE TITLE
--validation_stringency=LENIENT for GetHetCoverage

### ISSUE THREAD

**Issue by dlivitz** [broadinstitute/gatk-protected#373]
I am trying to run GATK ACNV on non-broad bams, and I run into this issue:

(in GetHetCoverage)
htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 65632, Read name HWI-ST467:139314245:C24PVACXX:6:2214:1855:52897, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned

This happens with every bam I tried from this center. 

The fix for this in previous versions of GATK was to use --validation_stringency=LENIENT 

But when I do this for GetHetCoverage I get: 
A USER ERROR has occurred: Invalid command line: validation_stringency is not a recognized option

I can't seem to find an equivalent parameter in the documentation. Is this still supported? 

-Dimitri

**Comment by akiezun** [comment]
can you try --VALIDATION_STRINGENCY LENIENT ?

**Comment by samuelklee** [comment]
Thanks for bringing this to our attention!  This isn't supported at the moment, but it looks like it should be pretty easy to add.  I'll give it a shot.

**Comment by dlivitz** [comment]
thank you! 
(just checked VALIDATION_STRINGENCY, it also complains)

**Comment by akiezun** [comment]
@samuelklee - see how it's done in gatk public.

**Comment by samuelklee** [comment]
Closed by #379.
