### ISSUE TITLE
Filter based on Gaussianity

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#380]
We filter targets with extreme variance, the idea being that tangent normalization did a poor job with these and our model is unreliable for them.  However, issue #378 will likely go a long way toward making this less of a concern.  One thing we don't filter on and perhaps should is not how much variance remains after tangent normalization but how Gaussian the coverage looks after tangent normalization.  Since our model assumes Gaussian copy ratio this amounts to filtering out targets for which our model is unsuitable.

We could implement this, for example, by filtering on the Anderson-Darling test statistic for each target.

**Comment by samuelklee** [comment]
Obviated by new coverage model.
