### ISSUE TITLE
Correct Tsv Reader/Writer reference javadoc documentation.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#39]
There some issues in the documentation text in package-info.java that was not updated properly after a last minute refactoring.

This task is neither nor not urgent.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2823](https://github.com/broadinstitute/gatk/issues/2823) via [**ZenHub**](https://www.zenhub.com/)
