### ISSUE TITLE
Evaluate using the Beagle het sites (based on 1kGp3) as our default het site list in pulldown

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#393]
We should probably use this as our default

http://bochet.gcc.biostat.washington.edu/beagle/1000_Genomes_phase3_v5a/

**Comment by samuelklee** [comment]
Done.  Made a list of 1kGp3 sites at minor-allele frequency >10% that seems better than the list we were previously using; the latter was limited to the exome and contained a large number of sites that were never pulled down.  New list gives ~30k hets with liberal pulldown, as opposed to ~18k from old list.  Evaluation on LUAD gives same MAE and RMSE, so looks like performance isn't affected.
