### ISSUE TITLE
ACNV on WGS workflow

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#395]
This includes ensuring that runtimes and RAM usage are acceptable.  

Leverage spark as needed.

**Comment by samuelklee** [comment]
As we discussed, ACNV as currently written (i.e., with MCMC) might choke if given ~1.6m hets GetHetCoverage currently finds in WGS samples with the BEAGLE SNPs list (typically we get ~30k in an exome).  We may have to bin or downsample, which could require some changes to the model-fitting code exclusive to WGS.

**Comment by LeeTL1220** [comment]
#567 will handle the spark-ification of GetBayesianHetPulldown.  Spark is no longer required, especially since some immediate users are confined to single core anyway.

**Comment by LeeTL1220** [comment]
Given that WGS does not look like it will speed up easily unless using Spark, not going to attempt more changes to improve speed for single core.

**Comment by LeeTL1220** [comment]
Therefore, #566 also closes this issue.
