### ISSUE TITLE
port M2

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk-protected#41]
M2 with its integration tests needs to be ported. depends on #40

**Comment by davidbenjamin** [comment]
This has been done.

**Comment by kcibul** [comment]
Hi David -- did you benchmark the port against the original?  I'd be interesting in seeing the results of the comparison

**Comment by davidbenjamin** [comment]
@kcibul We're working on it.  So far we haven't done anything to the algorithm, but it's very possible that the GATK4 assembly engine changes things.
