### ISSUE TITLE
Implement case sample "tangent normalization" for generative coverage model

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#430]
This is the part of the model that performs a single E step to find the posterior on the sample's position in latent space and then obtains likelihood functions for the copy ratio at each target.

**Comment by davidbenjamin** [comment]
This essentially means writing code that takes the new PoN and the case sample's raw read counts as input and outputs an implementation of the `TargetLikelihood` interface described in issue #533.

**Comment by LeeTL1220** [comment]
dependent on issue #432
