### ISSUE TITLE
Put generative coverage model into germline code

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#431]
Once issues #429 and #430 are handled this amounts to replacing the current emission in `CopyNumberTriStateHiddenMarkovModel` with the likelihoods produced by the generative coverage model, evaluated at copy ratios 1/2, 1, and 3/2.

**Comment by LeeTL1220** [comment]
Dependent on #432

**Comment by davidbenjamin** [comment]
I think @mbabadi is working on this.
