### ISSUE TITLE
Put generative coverage model into somatic code (part 1)

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#432]
Before integrating this with probabilistic segmentation, which is more complicated for somatic than for germline, we can simply replace the current tangent normalization step with the mode of the likelihood (as a function of copy ratio) resulting from the generative coverage model.  This requires issues #429 and #430 to be completed.

**Comment by davidbenjamin** [comment]
Also, this should only be attempted if we get good results from doing the equivalent in the germline code, issue #431.  After it is done somatic and germline will share a PoN and all associated code, including tangent normalization.

**Comment by LeeTL1220** [comment]
This only needs to be done if we stick with CBS for segmentation.  

At the very least, we need to implement this for checking performance against HMM.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2842](https://github.com/broadinstitute/gatk/issues/2842) via [**ZenHub**](https://www.zenhub.com/)
