### ISSUE TITLE
Create HDF universal jar

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk-protected#436]
It might be worth our time to build an HDF5-jni-universal jar which includes the java JNI code for HDF as well as the various native dynamic libraries for different platforms.  We could add a loader which knows how to load the appropriate native code for the platform, and package that along with binaries for common systems into a single jar.

We depend on certain libraries which do this already.  See org.xerial.snappy as an example.

We would allow for overriding the bundled native libraries on the command line in case we don't bundle the necessary one.

**Comment by droazen** [comment]
:+1: I think we should actually do this for all of our native dependencies.

**Comment by davidbenjamin** [comment]
Great idea!

**Comment by lbergelson** [comment]
Anyone who wants to do this talk to me first.

**Comment by akiezun** [comment]
@lbergelson i created https://github.com/broadinstitute/hdf5-java-bindings/pull/1 - please review

**Comment by akiezun** [comment]
replaced by https://github.com/broadinstitute/gatk/issues/1990
