### ISSUE TITLE
Crash in AllelicCNV due to infinite segment means

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#438]
``java.lang.IllegalArgumentException: Segment Mean must be finite.``

Happens when trying to convert ACNV sim final seg files into ACS seg file.  Only happens to some samples.

**Comment by samuelklee** [comment]
Outliers at log coverage of around -30 in small segments are throwing off the fit.  Will try a few things to fix this.

**Comment by samuelklee** [comment]
Also seems to be a problem more generally in small deletions (<5 events), even those that do not contain such extreme outliers, perhaps because of the artificially tight variance in these segments.
