### ISSUE TITLE
Add smoke tests for sparkJar / shadowJar

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk-protected#443]
I recently broke the ability to create a spark/shadow jar and only discovered it when I went to create one later.  We should add simple tests for the generated jar to be sure it can be created / executed.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2844](https://github.com/broadinstitute/gatk/issues/2844) via [**ZenHub**](https://www.zenhub.com/)
