### ISSUE TITLE
PlotACNVResults returns Success even when no file is generated.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#451]
A mismatch in the ACNV outputPrefix and the sampleName causes an error that prevents the PNG from being generated, but the tool still returns Success.  (Also, the plotting_dump.rda file that is generated is rather cryptic and isn't that helpful for debugging...)  Regardless of the error that prevents the PNG file from being generated, the tool should still fail if this happens.

Whether we should require that outputPrefix == sampleName is a separate issue.  I don't see why this should be the case, since we require that TN files only contain one sample.  Perhaps the real issue is that we use the sample name as the column header for the coverage column?

**Comment by samuelklee** [comment]
@achevali @LeeTL1220 @davidbenjamin one more nagging issue with the plotting to be aware of.  @achevali, maybe you can look at adding a fix for this as well?

**Comment by samuelklee** [comment]
@achevali, did you fix this in a recent PR, or should I leave it open?

**Comment by LeeTL1220** [comment]
@achevali Did you fix this already?

**Comment by samuelklee** [comment]
We had a forum user  bring this up: http://gatkforums.broadinstitute.org/gatk/discussion/comment/32781  I think we've also seen it ourselves a few times.  So it's still an open issue.
