### ISSUE TITLE
Question about LICENSE and use GATK-protected in custom software

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk-protected#455]
Hello,

I'm using the gatk non-protected framework/engine to develop some tools, and I would like to provide in the near future this tools in a uber-jar pacakge to run in the command line. I would like to have an open-source license in my code, and add as dependency the GATK4 framework.

Nevertheless, now I found that I can use some parts of the protected code in my program for avoiding reinvent the wheel. Concretely, the assembly and pair-HMM likelihood code in the `haplotypecaller` package will be useful for some of my tools. I would like to know how I can manage the licensing of my code if I use the GATK-protected as a dependency (just use the code as is, without modification) and if I can include the dependency in the uber-jar to make a complete jar file that could be run.

On the other hand, I would like to know how this could affect a publication of my tool in a research journal, citing of course the `HaplotypeCaller` method (if already publish or giving credit to Broad with the link to the GATK webpage). The main part of my tools won't include any part of the protected code, but if the program contains a tool which use some classes I don't know how this could affect.

I'm not a programmer/lawer by training, just I biologist without any knowledge of copyright things, and I'm struggling with the licensing with both the gatk public and protected. I hope that you could help me. Thanks a lot in advance.

Although not completely related with this, I also will also appreciate if you can tell me if there is a plan to make a Maven repository with the protected part of the toolkit, to manage in an easier way the dependencies.

**Comment by vdauwera** [comment]
Hi @magicDGS, I'm glad to hear you're finding the GATK4 framework useful for developing your own tools! That is definitely one of the key goals of the public module, to serve as a community resource to avoid wheel reinventions.

That being said, the protected module is subject to different constraints -- the license prohibits re-use and redistribution, even without modification, of all of that code. So right now what you'd like to do with the protected code, treating it as a dependency, is not legally possible. However, if you tell us exactly what parts of the code you'd like to use, perhaps we can find a way to enable you in your work. Sometimes we find that it makes sense to move some utility classes to the public module when they turn out to have a wider applicability than initially foreseen.

**Comment by akiezun** [comment]
Agreed, @magicDGS can you list exactly the classes you need? We may be able to push them down to the public part of gatk.

**Comment by magicDGS** [comment]
Thanks for the quick reply, @vdauwera and @akiezun. The utilities that I mention in my first question were the following:

* I'm planing to use the `AssemblyRegionWalker` from the public module, to perform local assembly of small windows. For that purpose, I found that in the protected module you have the `ReadThreadingAssembler`, that will be much easier to use than implement an assembler by myself.
* Second, I mention the pair-hmm likelihood code, but I've just realize that the part of that code that I need is already in the public repository (with the `PairHMM` interface implementation).

I will be very grateful if the assembly code could be move to the public module, but I fully understand if not. I'm afraid that it will not be possible because I belive that the assembly code is one of the algorithms property of Broad.

**Comment by akiezun** [comment]
I'll figure it out

**Comment by magicDGS** [comment]
@akiezun, do you already have some idea about this? Thank you very much!

**Comment by magicDGS** [comment]
@akiezun, do you already know something about if the `ReadThreadingAssembler` could be public?

Thank you in advance!

**Comment by vdauwera** [comment]
Hey @magicDGS, @akiezun is not with the team anymore, so let me find that out for you.

**Comment by magicDGS** [comment]
Thanks @vdauwera!

**Comment by magicDGS** [comment]
I think that I do not need the `ReadThreadinfAssembler` anymore because I can use the fermi-lite JNI, which is under BSD.

Thank you very much for your help.
