### ISSUE TITLE
HaplotypeCaller - running on CRAM is super slow

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk-protected#467]
tag 39c988c2dc7f669306d246a2191d16af50496640
1. Make a cram file like this (in our src/test/resources/large):
   `samtools view -C -T human_g1k_v37.20.21.fasta -o CEUTrio.HiSeq.WGS.b37.NA12878.20.21.cram CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam`
   `samtools index CEUTrio.HiSeq.WGS.b37.NA12878.20.21.cram`
2. run HC on it and compare with BAM:

```
./gatk-launch HaplotypeCaller -I ~/IdeaProjects/gatk/src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.cram -L 20:1-11000000 -R ~/IdeaProjects/gatk/src/test/resources/large/human_g1k_v37.20.21.fasta  -O testa.cram.g.vcf -ERC GVCF --bamOutput testa.cram.outHC.bam
```

time BAM : 0.7 minutes
time CRAM: 3.81 minutes

**Comment by droazen** [comment]
What if you run without `--bamOutput`? Is it still slow?

**Comment by droazen** [comment]
In addition to testing without `--bamOutput`, you should also try it with a `.bai` index on the cram, as @cmnbroad has identified issues with the current `.crai` support in htsjdk.

**Comment by akiezun** [comment]
yes, still super slow without `--bamOutput`

**Comment by akiezun** [comment]
Should we blow up on crai and say it's unsupported for now? (better that than produce bogus results). Also, how do i make a bai file for a cram file?

**Comment by droazen** [comment]
@akiezun I defer to @cmnbroad on whether the issues with `crai` are bad enough to warrant such an approach. 

You should be able to make a `bai` on the cram by running GATK `PrintReads` on it.

**Comment by cmnbroad** [comment]
I'm still looking for the smoking gun where a query fails using a .crai, but I haven't found one yet; but the BAMIndex metadata is cerrtainly wrong after conversion from .crai. If we do decide to run off .crai, we should do it in htsjdk.

To make a .bai,  just use GATK PrintReads to create the .cram.

**Comment by akiezun** [comment]
still super slow using .bai : 3:51 minutes

**Comment by droazen** [comment]
@akiezun Can you try increasing the -Xmx value to something ridiculous (like 32G) just to eliminate memory usage as a variable here?

**Comment by droazen** [comment]
(and run on a machine with large memory like gsa6)

**Comment by akiezun** [comment]
Let's collect problems first, then (tomorrow maybe) go over those discovered and make a list of showstoppers for alpha1.

**Comment by droazen** [comment]
This and https://github.com/broadinstitute/gatk/issues/1787 imply that there might have been a CRAM performance regression in htsjdk recently -- we should test with a bunch of GATK revisions from before each successive htsjdk update to see if there was one that killed CRAM performance. I don't recall seeing a big BAM vs. CRAM performance difference when we first hooked up CRAM support to GATK...

**Comment by droazen** [comment]
@cmnbroad Could you have a look at this when you have time?

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2850](https://github.com/broadinstitute/gatk/issues/2850) via [**ZenHub**](https://www.zenhub.com/)
