### ISSUE TITLE
SparkGenomeReadCount should have more intelligent blacklisting that can support other genome builds.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#471]
Currently, the tool can only exclude by X,Y, MT contigs.  This is okay for humans, but not necessarily useful for other reference genomes.

**Comment by akiezun** [comment]
Just use the standard -L which we use everywhere else. It's handled
automatically by the engine

On Wednesday, April 27, 2016, Lee Lichtenstein <notifications@github.com>
wrote:

> Currently, the tool can only exclude by X,Y, MT contigs. This is okay for
> humans, but not necessarily useful for other reference genomes.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gatk-protected/issues/471>
>


-- 
Sent from Gmail Mobile

**Comment by LeeTL1220** [comment]
@akiezun That will automatically filter the reads that come into the tool?  We looked at ``-L`` and did not think we could use it.  @achevali , do you remember why we did not use ``-L`` in the WGS Coverage tool for blacklisting contigs?
