### ISSUE TITLE
Determine list of TGCA samples with events that overlap the gene-panel.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#479]

**Comment by vruano** [comment]
I had come with the following 30 samples list.

For this, first I found those events in the GenomeSTRiP output file that overlap with the eMerge targets (needed to clean their file up as some of the targets therein overlap). 

Then I only consider event with a frequency equal or less than 5% and that they are not multi-allelics. 

The list below are the sample names with the number of qualifying events for which they have a non-ref call:

<pre>
      2 TCGA-05-4396-10A-01D-1855-08
      2 TCGA-06-0157-10A-01D-1491-08
      1 TCGA-06-2570-10A-01D-1495-08
      2 TCGA-14-2554-10A-01D-1494-08
      4 TCGA-41-5651-10A-01D-1696-08
      3 TCGA-44-6148-10A-01D-1753-08
      1 TCGA-50-5066-10A-01D-1625-08
      1 TCGA-64-1680-10A-01D-1040-01
      3 TCGA-67-6215-10A-01D-1753-08
      7 TCGA-78-7146-10A-01D-2036-08
      4 TCGA-78-7156-10A-01D-2036-08
      5 TCGA-78-7535-10A-01D-2063-08
      3 TCGA-85-8052-10A-01D-2244-08
      1 TCGA-92-8064-10A-01D-2244-08
      1 TCGA-BJ-A28V-10A-01D-A19M-08
      3 TCGA-BR-8373-10A-01D-2341-08
      2 TCGA-CD-8529-10A-01D-2341-08
      1 TCGA-D7-8570-10A-01D-2341-08
      2 TCGA-DJ-A2Q1-10A-01D-A19M-08
      1 TCGA-E1-5319-10A-01D-1893-08
      1 TCGA-EE-A3JI-10A-01D-A21A-08
      1 TCGA-EM-A3AQ-10A-01D-A20C-08
      1 TCGA-ER-A3ES-10A-01D-A20D-08
      1 TCGA-FK-A3SE-10A-01D-A22D-08
      1 TCGA-G9-6365-10A-01D-1786-08
      1 TCGA-HC-7075-10A-01D-1961-08
      9 TCGA-HC-7740-10A-01D-2115-08
     17 TCGA-HC-7744-10A-01D-2115-08
      1 TCGA-HC-8258-10A-01D-2260-08
      1 TCGA-HT-7602-10A-01D-2086-08
</pre>

**Comment by vruano** [comment]
I have not filtered based on the number of covered targets per event; most events are just 1 target long.

There is a total of 23 events:

<pre>
CONTIG	START	END	CALL	NTARGETS	FREQ 
1	98189364	98367000	-	1	0.0118
1	152281652	152285321	-	1	0.0118
2	40964269	41009870	-	1	0.0235
4	3467857	3473907	+	1	0.0176
4	135131038	135144309	-	1	0.0235
5	1278704	1282903	+	1	0.0059
5	117481014	117533455	-	2	0.0353
5	137414773	137438999	+	1	0.0235
7	117433225	117461146	+	1	0.0059
9	132573663	132583864	+	1	0.0176
11	25218746	25281154	-	1	0.0353
11	115114026	115215423	-	1	0.0118
11	126233892	126246747	+	1	0.0235
11	126241786	126243947	+	1	0.0353
11	126243948	126248222	+	1	0.0353
16	15798209	15950545	+	41	0.0118
16	58680867	58683738	+	1	0.0118
17	794232	801799	+	1	0.0176
17	79571368	79630302	+	1	0.0059
18	52875546	52956230	-	11	0.0176
19	54504608	54513753	+	1	0.0412
20	44348793	44354658	-	1	0.0353
21	35670115	35991982	-	3	0.0059
</pre>

**Comment by vruano** [comment]
@davidbenjamin @LeeTL1220 please comment.

**Comment by LeeTL1220** [comment]
Well, a 30 sample list is okay.  When you say, 

> Then I only consider event with a frequency equal or less than 5% and that they are not multi-allelics. 

Were you referring to 5% in the 170 samples or 5% in the general population?  I assume the former, but want to make sure.

**Comment by vruano** [comment]
the former

**Comment by LeeTL1220** [comment]
@vruano @davidbenjamin I am trying to get all 170 sequenced.

**Comment by LeeTL1220** [comment]
Working it out.  List has been sent.
