### ISSUE TITLE
Create versions of the ParamUtil methods that throw UserExceptions

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#482]
We would like to use ParamUtils to handle poor user input on CLI classes.  In this case, we want to throw a ``UserException.XXXXX`` rather than an InvalidArgumentException.

In its current form, since it only throws InvalidArgument exceptions, ParamUtils can only be used in backend classes.

**Comment by samuelklee** [comment]
@LeeTL1220 Can we close?  I think we have been using `validateArg` instead.
