### ISSUE TITLE
Change representation of target/copy-ratio segments in GATK CNV output.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#485]
For legacy reasons, the copy-ratio segments reported by CNV are specified as "end of first target in segment--end of last target in segment," rather than the more natural "start of first target in segment--end of last target in segment."  One reason for this is because the R script responsible for segmentation acts on a list of genomic locations, rather than intervals, so we pass only the target ends during the target-segmentation step.

However, it's trivial to look up the target starts in the original list of targets and restore this information before writing the segment file.  In fact, this is already done by ACNV when taking in the segment files output by CNV---the reasoning here being that hets falling in the first target of each copy-ratio segment would otherwise not be grouped with the correct segment.

If no legacy pipelines/scripts will be affected, it makes more sense to perform this step in GATK CNV---specifically, in the PerformSegmentation tool.

**Comment by LeeTL1220** [comment]
@samuelklee I don't *think* anything legacy would be affected.  Maybe some evaluation script somewhere.  @achevali What do you think?
