### ISSUE TITLE
Merge consecutive events in the truth en Germline Evaluation tool.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#492]
Currently if the truth (GenomeSTRiP vcf variants) are contiguous in target space we do not merge them thus they would count as several independent truth events when there is no way that an exome based tool would ever see them that way.

This issue is about adding an option so that these event can be merged.

This cannot be iniciated until the evaluation code has been merged into master.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2852](https://github.com/broadinstitute/gatk/issues/2852) via [**ZenHub**](https://www.zenhub.com/)
