### ISSUE TITLE
Expand allelic PoN to account for site-specific distributions of reference bias across samples.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#497]
Under certain assumptions/approximations about these distributions, this would just require a minor modification of the existing code/model.

**Comment by samuelklee** [comment]
perhaps alpha-2.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2854](https://github.com/broadinstitute/gatk/issues/2854) via [**ZenHub**](https://www.zenhub.com/)
