### ISSUE TITLE
Create MAF-CR plots for ACNV.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#498]
Specifically, a scatter plot of ACNV segments in 2D MAF-CR space + histograms for their 1D projections.  This will be useful for downstream tools.

**Comment by samuelklee** [comment]
as an example:
![maf-cr-purity-deciles](https://cloud.githubusercontent.com/assets/11076296/15189893/24556cd6-177b-11e6-8374-78d9a9b0e9a6.png)

**Comment by samuelklee** [comment]
Would be great to have this per chromosome as well.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2855](https://github.com/broadinstitute/gatk/issues/2855) via [**ZenHub**](https://www.zenhub.com/)
