### ISSUE TITLE
POS -> POSITION change in pulldown column name breaks plotting.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#499]
This change was made in #444.  Also breaks evaluation scripts.  @LeeTL1220, is backwards compatibility with previous pulldowns desired?  See also #451.

**Comment by mbabadi** [comment]
If backwards compatibility is not required, we only need to replace POS with POSITION in `CNV_plotting_library.R` (3 instances) to make sure everything works. The current behavior is that `ANCVPlotterUnitTest' passes but creates empty plots (R 3.2.4). For @achevali, the unit tests fail (R 3.0.3). If we have a consensus, either going back to POS, or moving forward with POSITION, I suggest updating master ASAP.
