### ISSUE TITLE
Case-only het pulldown for cell lines

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#508]
Currently, the tumor only het pulldown assumes purity of < 1.0.  However, cell lines do have a purity of 1, so we would expect poor performance in some regions.

**Comment by samuelklee** [comment]
@LeeTL1220 @mbabadi can you close if appropriate?

**Comment by mbabadi** [comment]
We haven't addressed this issue yet; we haven't thought much about it
either. I'd say leave it open until we decide whether or not we want to do
something about it. @LeeTL1220 what do you think?

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2856](https://github.com/broadinstitute/gatk/issues/2856) via [**ZenHub**](https://www.zenhub.com/)
