### ISSUE TITLE
Expose segmenter parameters in WDL case sample workflow

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#520]
We should expose all the segmenter parameters, since we will need it for WGS.

Also, update the json template to reflect new default values.

**Comment by asmirnov239** [comment]
These are default parameters right now that need to be passed to the PerformSegmentation task
--alpha 0.01 --nperm 10000 --pmethod HYBRID --minWidth 2 --kmax 25 \
--nmin 200 --eta 0.05 --trim 0.025 --undoSplits NONE --undoPrune 0.05 --undoSD 3
