### ISSUE TITLE
WGS workflow evaluation

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#524]
- [ ] File issues for evaluations (and make sure each evaluation is described, including ground truth).  Make sure that there is a milestone and assignee for each.

Need to show some measure of performance for the WGS evaluation (GATK CNV only.  Not ACNV)

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2858](https://github.com/broadinstitute/gatk/issues/2858) via [**ZenHub**](https://www.zenhub.com/)
