### ISSUE TITLE
Give ReadCountCollection some features of TargetCollection

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#531]
`ReadCountCollection` should be able to query all targets / records in a given interval.  This will eliminate some unnatural-looking code, in particular anything involving `ReadCountRecord.SingleSampleRecord`.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2859](https://github.com/broadinstitute/gatk/issues/2859) via [**ZenHub**](https://www.zenhub.com/)
