### ISSUE TITLE
Create plots to justify approximations

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#538]
. . . or maybe an interaction IPython notebook.

The approximations are
* the gamma likelihood approximation in the allele fraction model that allows exact integration over bias
* the Poisson -> normal approximation in the new coverage model

**Comment by mbabadi** [comment]
The second is already done in my branch mb_updated_coverage_docs

**Comment by davidbenjamin** [comment]
Great!

**Comment by davidbenjamin** [comment]
The first one closed by PR #546.
