### ISSUE TITLE
test suite just fails on macOS X - due to HDFS and R

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk-protected#549]
the test suite should not just fail - the HDF5 test should either be made to pass or be skipped. Same for R tests

@LeeTL1220 can you fix this or find someone?

**Comment by lbergelson** [comment]
Did you do the setup stuff in the readme?  It's supposed to work on mac if you've done that stuff.

**Comment by akiezun** [comment]
yup, user error
