### ISSUE TITLE
Is there an issue with deeper coverage tumors?

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#557]
On some samples sequenced with deeper coverage, a large amount of noise has been seen.  This could easily be due to poor representation in the PoN, but we need to confirm.

**Comment by mbabadi** [comment]
Is the noise relatively uniform across all targets, or mostly in regions with CNV events? Are these samples produced by the exact same sequencing pipeline? it is possible that deeper coverage => longer PCR time (?) => different GC bias curve that is not compatible with the PoN, in which case, I suppose GCCorrector could help?

**Comment by LeeTL1220** [comment]
Let's close for now until we get more examples....
