### ISSUE TITLE
Spark-ify ``GetBayesianHetPulldown``

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#567]
Waiting on improvements in the GATK engine that will be in place for HaplotypeCaller.

The issue is that partitions cannot share reads, which is problematic for intervals (SNP sites) near the edge of a partition.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2861](https://github.com/broadinstitute/gatk/issues/2861) via [**ZenHub**](https://www.zenhub.com/)
