### ISSUE TITLE
HaplotypeCaller: implement Allele Specific mode for VCFs

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk-protected#576]
Allele Specific mode for VCFs is currently not implemented. the task is to add that mode - requires porting the code for combining annotations

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2864](https://github.com/broadinstitute/gatk/issues/2864) via [**ZenHub**](https://www.zenhub.com/)
