### ISSUE TITLE
enable --includeNonVariantSites GenotypeGVCS option

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk-protected#580]
Update genotype gvcfs so includeNonVariantSites can be enabled.  This may be easiest by implementing a different walker type to match the old LocusWalker behavoir but could also be done by accumulating sites as it goes.

**Comment by lbergelson** [comment]
this is blocked by  broadinstitute/gatk#2429

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2865](https://github.com/broadinstitute/gatk/issues/2865) via [**ZenHub**](https://www.zenhub.com/)
