### ISSUE TITLE
delete files that were moved to gatk

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk-protected#598]
We currently have files that were moved from gatk-protected to gatk but never deleted in gatk-protected.   See https://github.com/broadinstitute/gatk/pull/1888.  Since these moved without changing packages we have duplicate files with the same exact identifiers.  We should figure out how to prevent this in the future, possibly by giving gatk-protected its own package.  

We should check the affected files before deleting because I think there may have diverged from the versions in public.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2869](https://github.com/broadinstitute/gatk/issues/2869) via [**ZenHub**](https://www.zenhub.com/)
