### ISSUE TITLE
Port bug fix for GVCF block merging.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#602]
See https://github.com/broadinstitute/gsa-unstable/pull/1431.

**Comment by samuelklee** [comment]
Also see broadinstitute/gsa-unstable#1440.

**Comment by samuelklee** [comment]
@lbergelson were these fixes ported?

**Comment by lbergelson** [comment]
@samuelklee I don't think so, not by me at least.

**Comment by ronlevine** [comment]
@samuelklee Would you like me to do the port? It will require both gatk and gatk-protected changes.

**Comment by samuelklee** [comment]
If you don't mind, @ronlevine---I probably won't get around to it for a bit.  Not high priority though, I was just going through and cleaning up issues.

**Comment by ronlevine** [comment]
Will do.

**Comment by ronlevine** [comment]
Closing since https://github.com/broadinstitute/gatk/pull/2619 is merged.

**Comment by ronlevine** [comment]
Reopening since need to do the protected part.

**Comment by samuelklee** [comment]
Also note that https://github.com/broadinstitute/gsa-unstable/pull/1451 should be included in this port.

**Comment by ronlevine** [comment]
The HaplotypeCaller tests that compare the output GVCFs between the current code and GATK 3.5 will not pass. This is due the block merging fix. So, I generated output files with with a version of GATK 3 that has this fix, 3.7-42-gbe6a37c. If it's premature for these tests, I can disable them.

**Comment by droazen** [comment]
Please don't either disable these tests or move them to GATK 3.7 outputs just yet -- this would be disruptive to my current efforts to figure out what's behind some annotation differences in the GATK4 HaplotypeCaller. I do plan to migrate the tests to 3.7 outputs soon, but I need to study the diffs a bit first.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2870](https://github.com/broadinstitute/gatk/issues/2870) via [**ZenHub**](https://www.zenhub.com/)
