### ISSUE TITLE
Fix comments in wdl template json file

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#603]
Comments are not supported in json.  These need to be removed.

**Comment by asmirnov239** [comment]
@LeeTL1220 I can close this. Does it make sense to leave json files intact, as they are just templates, and provide details on how to generate them in the README.md ?

**Comment by LeeTL1220** [comment]
@asmirnov239 No need.  I am making some changes.  I'll make a json template that can be run with string Template classes in python.  And I'll make a little doc detailing each field.
