### ISSUE TITLE
Cause workflows to fail immediately if HDF5 cannot be loaded (at start)

### ISSUE THREAD

**Issue by achevali** [broadinstitute/gatk-protected#605]
Especially Widdle

**Comment by akiezun** [comment]
tools will now immediately fail with UserException. This was fixed in #622

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2871](https://github.com/broadinstitute/gatk/issues/2871) via [**ZenHub**](https://www.zenhub.com/)
