### ISSUE TITLE
Absolute compatibility issue

### ISSUE THREAD

**Issue by dlivitz** [broadinstitute/gatk-protected#617]
Hi GATK team, 

There is a small issue with the ACS style output of GATK-ACNV
Segments that have non-nan values for mu major and mu minor but nan values for sigma cause ABSOLUTE to crash.

The fix would be to output the segments as NaN for mu major, mu minor and f if any of the other values are NaN. 

(In this case it was a segment with a length of 3 targets)

-Dimitri

**Comment by samuelklee** [comment]
Thanks for bringing this to our attention, @dlivitz!  Perhaps you can send me some test files and a more detailed description and I'll take a look.

**Comment by samuelklee** [comment]
@dlivitz took a look at this today and think I have a quick fix.  Can you confirm one thing for me though---was this segment called as balanced?

**Comment by samuelklee** [comment]
@dlivitz See a possible fix in #647.  If you could build the jar and confirm (or provide me with a test file so I can do it myself), that'd be great!
