### ISSUE TITLE
Sample names with underscore or period get truncated.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#636]

**Comment by samuelklee** [comment]
I think this is actually due to the CalculateTargetCoverage tool, which has this:

    @Override
        public String toString() {
            return name().toLowerCase().replace("_", " ");
        }

So sample names with underscores are actually split with spaces, which screws up parsing of column headers and sample-name retrieval in subsequent steps.  @vruano I think this is your code---why was it necessary to replace underscores with spaces?

**Comment by samuelklee** [comment]
@asmirnov239 If you decide to tackle this, it occurs to me that it might be better to just store the sample name in a header comment.

**Comment by samuelklee** [comment]
Just to record and clarify a few things we discussed:

-I think that all files we generate for individual case samples---"ReadCountCollection" files for coverage profiles, "AllelicCountCollection" files for het pulldowns, and segment files---should contain the sample name as metadata in a header comment with a common tag (e.g., `#sampleName = ...`).  Currently, these sample names are stored in column headers, in the fields of a `SAMPLE` column, or not at all, depending on the type of file.

-CLIs that generate a file from an input BAM (`CalculateTargetCoverage`, `GetHetCoverage`, etc.) should take the sample name from that BAM by default.  Since these are the first steps in our workflows, we could also optionally allow the user to specify a sample name different from that in the BAM.

-CLIs that take multiple non-BAM input files should check for consistency of the sample names as part of the argument validation step.

-CLIs that output the sample name in plots should derive these from the header comment.

-For files that contain data multiple samples (e.g., the output of `CombineReadCounts`), we can probably leave the sample names in the column headers, but it would be nice to output the type of data stored in a header comment as well (e.g., `PCOV` or `RAW`).  At some point I think we should restrict to `RAW` output only, see #615.

-Entity names specified by the input file to the WDLs can be separate from the BAM sample names by default.  If we allow the user to optionally specify sample names as described in the first bullet point, we can set up the WDL to pass the entity names.

**Comment by asmirnov239** [comment]
Moved to a new issue #751
