### ISSUE TITLE
Move readMatrix methods from PoN class to HDF5File in hdf5-java-bindings.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#637]
I moved these into HDF5File in my branch, but HDF5File was moved to hdf5-java-bindings before I could merge.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2876](https://github.com/broadinstitute/gatk/issues/2876) via [**ZenHub**](https://www.zenhub.com/)
