### ISSUE TITLE
ClusteringGenomicHMMSegmenter can fail if random memory length exceeds maximum allowed.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#640]
This combined with an unset random seed was causing `AlleleFractionSegmenter.testChromosomesOnDifferentSegments` to fail intermittently in #633.  @davidbenjamin could you take a look when you get back?  This could be fixed easily by a `Math.min` in the right place, but I don't know if the fact that the memory length seems to blow up is something generic that happens when we collapse to a single state that needs to be addressed more carefully.

**Comment by samuelklee** [comment]
@davidbenjamin can you take a quick look?  I think it's probably a quick fix.

**Comment by davidbenjamin** [comment]
Sure.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2877](https://github.com/broadinstitute/gatk/issues/2877) via [**ZenHub**](https://www.zenhub.com/)
