### ISSUE TITLE
Determine and document best practices for CNV..

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#644]
We currently have some recommendations for coverage collection that were based on recapseg, but it would be good to revisit them with GATK CNV and the new coverage model/HMM segmentation.  In addition, GC bias correction has been implemented in the workflow, but it is not yet evaluated.

Documentation and and scripts to generate evaluations and plots showing the effects on GATK CNV, the new coverage model, and downstream tools (e.g., ACNV) are needed.
- [ ] target padding
- [ ] keeping duplicates
- [ ] GC bias correction
- [ ] sequence repeat correction
- [ ] target filtering

**Comment by samuelklee** [comment]
I am planning on removing sequence repeat correction to close #645.  We can reimplement and reevaluate in the future.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2881](https://github.com/broadinstitute/gatk/issues/2881) via [**ZenHub**](https://www.zenhub.com/)
