### ISSUE TITLE
Parameters for aliased tasks in WDL scripts not set correctly by json.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#648]
e.g., NormalizeSomaticReadCounts.mem, CalculateTargetCoverage.transform?  Or I might just be running the scripts incorrectly.  @asmirnov239 can we discuss when you're back?

**Comment by asmirnov239** [comment]
Thank for pointing that out. The parameters seems to be overridden inside of script itself. I can definitely fix it and expose whatever parameters need to be changed.  Definitely, we can discuss it whenever you have time!

**Comment by asmirnov239** [comment]
Seems like you have to add a separate variable in json for all aliased tasks, so I'm just going to make all necessary exposed variables in the workflow itself

**Comment by asmirnov239** [comment]
Closed by pull request #657
