### ISSUE TITLE
Blacklist PAR regions in TargetCoverageSexGenotyper

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#653]
Issue: cross reads from X to Y in PAR regions lead to problematic sex inferences. In a cohort of 112 sex annotated samples, a single XX -> XY misclassification was noticed, which was identified to be due to large number of reads aligned to the Ychr PAR region.

Solution: the tool must take an interval list for "blacklisted regions" and neglect targets lying in that region while calculating likelihoods of different sex genotypes.

**Comment by ldgauthier** [comment]
Unfortunately Shaila, who's been visiting the MacArthur lab for a few months, isn't around much longer.  She did a lot of chrX work in grad school and we talked a lot about variant filtering strategies for X.  There is an interval list for the PAR in UCSC or somewhere similar, but she said that according to population genetics theory, it's not static so it will be slightly different in different individuals and will change with time (probably dozens of generations at least.)  I think for your purposes the published intervals will probably be fine, but I wanted to note that the PAR isn't perfectly defined.

**Comment by mbabadi** [comment]
Thanks @ldgauthier, interesting huh... I'm curious to understand the microscopic mechanism responsible for the drift of PARs in the offsprings. Anyway, like you said, we'll be fine working with published intervals (we can also pad them a bit for good measure). Also, the PAR "blacklist" table is going to be a flexible user input.

**Comment by ldgauthier** [comment]
And Konrad pointed out there's a PAR3 in some people (about 2% of the population): http://link.springer.com/article/10.1007%2Fs10142-013-0323-6  Chromosome X is like the wild west.  But Monkol is super excited about CNV calls on X!

**Comment by mbabadi** [comment]
This is addressed in https://github.com/broadinstitute/gatk-protected/pull/695
Closing.
