### ISSUE TITLE
Optimize allele-fraction model

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#662]
See comments in #660.  Runtime is now about 30-40 minutes for an exome with default parameters, which is a little high.

I think we could explore implementing a version of the AF model where the reference bias is not integrated out.  This might require more iterations to converge, but on the other hand conditional likelihoods might be cheaper to calculate.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2884](https://github.com/broadinstitute/gatk/issues/2884) via [**ZenHub**](https://www.zenhub.com/)
