### ISSUE TITLE
CalculateTargetCoverage command line printed in header of output is incorrect.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#663]
--groupBy parameter is output in lowercase, but is required to be input as uppercase.  Thus, if one tries to rerun the printed command line, an exception will be thrown.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2885](https://github.com/broadinstitute/gatk/issues/2885) via [**ZenHub**](https://www.zenhub.com/)
