### ISSUE TITLE
Code duplication of isActive() between HaplotypeCaller and Mutect2

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#669]
`Mutect2AssemblyRegionEvaluator` and `HaplotypeCallerEngine` share very similar `isActive()` methods.  Extract a common method to a utils class.

Note that this ticket is not necessarily trivial because `isActive()` need not be entirely the same for germline and somatic variants.  Thus the extracted method may need to be passed parameters that differ between the two cases.  However, if the current implementation doesn't distinguish between the case we can extract an identical shared method as a first pass.

**Comment by davidbenjamin** [comment]
@droazen What's your opinion on the best way to deal with duplicated M@ and HC code? Put shared static methods in a utils class? Have M2 and HC's engines extend a common abstract class?  Make methods in HC public and have M2 use them?  None of the above?

**Comment by droazen** [comment]
@davidbenjamin Shared static utility methods is the most flexible approach (least likely to create problematic entanglements). In general with GATK4 we've tried to extract "engine" functionality into standalone utilities that can be used (for example) regardless of whether you're a walker or a spark tool. The static method `AssemblyRegion.createFromReadShard()` is a good example of this -- previously this code was embedded in the active region traversal, but as a standalone method it can easily be called from both the walker and spark versions of `HaplotypeCaller`.

**Comment by davidbenjamin** [comment]
Upon further inspection of the code, `isActive()` is quite different and no shared code needs to be extracted.
