### ISSUE TITLE
Weight MAF on Het SNPs by their likelihoods in segmentation and MAF modelling

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#683]
The coverage on Het SNPs has a significance variance in WES data. One of the columns in the output of GetBayesianHetCoverage is the log likelihood of that site being a Het SNP (in normal Het pulldown). Similarly, the upcoming Mutect2 will give a similar log likelihood measure on tumor Het SNPs. We can use this information to (1) give higher weight to more reliable Hets, and also (2) use the log likelihood in the emission model for HMM-based segmentation of MAFs.

**Comment by mbabadi** [comment]
@davidbenjamin @samuelklee what do you guys think? it shouldn't take too much effort. I guess the real question is -- do we want to invest more time on enhancements that primarily address issues with WES data?

**Comment by samuelklee** [comment]
Closing, new allele-fraction model will most likely marginalize over genotype.
