### ISSUE TITLE
HaplotypeCaller should override getDefaultReadFilters instead of makeReadFilter

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk-protected#688]
With the changes to read filters in protected, `HaplotypeCaller` should override `getDefaultReadFilters` instead of `makeReadFilter` in order to allow users to add/remove filters.  This requires moving some arguments from haplotype caller args into the appropriate read filter.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2888](https://github.com/broadinstitute/gatk/issues/2888) via [**ZenHub**](https://www.zenhub.com/)
