### ISSUE TITLE
Some M2 filters unknown to GATKVCFHeaderLines

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#691]
`GATKVCFHeaderLines` has a giant static block defining `VCFHeaderLines` in which several M2 filters do not appear, causing `getFilterLine` to return `null`.  These filters are the clustered read position filter, the triallelic filter, and the strand artifact filter.
        
The required fix would be in the GATK public repo.

**Comment by takutosato** [comment]
Fixed by broadinstitute/gatk#2188
