### ISSUE TITLE
Remove NON_REF from allSites VCF output

### ISSUE THREAD

**Issue by ronlevine** [broadinstitute/gatk-protected#692]
Port https://github.com/broadinstitute/gsa-unstable/pull/1470.

**Comment by ronlevine** [comment]
This will have to wait since -allSites is not yet supported.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2889](https://github.com/broadinstitute/gatk/issues/2889) via [**ZenHub**](https://www.zenhub.com/)
