### ISSUE TITLE
Mutect2 DREAM Challenge WDL

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#693]

**Comment by takutosato** [comment]
Blocked by [#2202](https://github.com/broadinstitute/gatk/issues/2202) in GATK public

**Comment by takutosato** [comment]
No longer blocked

**Comment by davidbenjamin** [comment]
@takutosato Now that you finished this, let's get the wdl script in the repo.  Whenever you feel your script looks good enough, submit a PR and I'll review.

**Comment by davidbenjamin** [comment]
Closed by Takuto in PR #823.
