### ISSUE TITLE
See if CountSet can be replaced with an existing set implementation

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk-protected#698]
`CountSet` is a small class that is only used in 1 place.  Investigate if it can be replaced with a set from one of our many collection libraries.  It needs to implement an efficient max and min operation.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2890](https://github.com/broadinstitute/gatk/issues/2890) via [**ZenHub**](https://www.zenhub.com/)
