### ISSUE TITLE
Better implementation of CNV-avoidance regularizer for unevenly spaced targets

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#701]
The present implementation of the CNV-avoidance regularizer in the new coverage model assumes evenly spaced targets on a single contig. It does not take into account the fact that targets on different chromosomes are "infinitely" separated. Agilent/Ice targets are very unevenly spaced and the distribution of target spacing has a heavy tail, making the matter worse.

The regularizer could still be used with certain modifications. Let us define the "target coverage noise" for sample s as:

u_{st} = \sum_{\mu} W_{t \mu} z_{s \mu} + m_t

(1) [implementation] First of all, the target coverage noise must be regularized on each contig separately. It doesn't make sense to stack up all targets and take once giant FFT of u_{st}. This can be fixed in the current implementation with little effort.

(2) [formal development + implementation] Within each contig, u_{st} must be mapped from target space to genomic position space e.g. via kernel density estimation. It is crucial to take into account the uncertainty in density estimation in the penalty function. For example, if the pre-image of a genomic position $x$ lies at the middle of a certain target $t$, the estimated value is much more reliable than the case where it lies between two largely separated targets. The penalty must be weighted according to the certainty of estimation.

(3) [formal development + implementation] once step 1 and 2 are done, the iterative solver code must be updated accordingly.

**Comment by mbabadi** [comment]
@samuelklee @davidbenjamin @asmirnov239 Let's have a joint meeting at some point to discuss the problem. It is (probably) not too hard to figure out, and it will make our model really shine!

**Comment by mbabadi** [comment]
I have some notes written on this which I can discuss tomorrow in the CNV meeting.

**Comment by mbabadi** [comment]
Here's a nice demonstration @asmirnov239 @samuelklee @davidbenjamin. The first sample is denoised with 2 principal components, the second with 8 principal components. The obvious deletion events are gone. According to Genome STRiP, these are indeed common events.
![chr_3_events](https://cloud.githubusercontent.com/assets/15305869/18856312/bf2bae00-8427-11e6-9342-7292d94cd769.png)
![chr_3_no_events](https://cloud.githubusercontent.com/assets/15305869/18856314/c287f2ca-8427-11e6-8b4f-13cce2fb2f72.png)

**Comment by mbabadi** [comment]
@asmirnov239 this looks very much like your simulated data -- there will be a significant penalty associated to picking up those deletions as noise.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2892](https://github.com/broadinstitute/gatk/issues/2892) via [**ZenHub**](https://www.zenhub.com/)
