### ISSUE TITLE
Port fix 1475 from GATK3

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/gatk-protected#706]
[Here](https://github.com/broadinstitute/gsa-unstable/pull/1475), but the alt allele removal functions must be ported to protected first, preferably by the original author @vruano.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2893](https://github.com/broadinstitute/gatk/issues/2893) via [**ZenHub**](https://www.zenhub.com/)
