### ISSUE TITLE
Detect anomalous samples during/after coverage PoN creation

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#710]
It happens often that the users attempt to make a coverage PoN from samples that come from different sequencing platforms, for example, let say platforms A and B. In this situation, some principal components will have strong projections onto A, and some onto B. We need to be able to identify such anomalies, either during PoN creations or in a post-processing step.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2895](https://github.com/broadinstitute/gatk/issues/2895) via [**ZenHub**](https://www.zenhub.com/)
