### ISSUE TITLE
Improve the performance of forward-backward algorithm by caching emission likelihoods

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#711]
The title says it all. Emission probability calculation is quite expensive in the new coverage model and we need many such calls (in particular for random sampling).

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2896](https://github.com/broadinstitute/gatk/issues/2896) via [**ZenHub**](https://www.zenhub.com/)
