### ISSUE TITLE
What actions need to be taken knowing that the Docker image has vulnerabilities (according to dockerhub)?

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#712]
https://hub.docker.com/r/broadinstitute/gatk-protected/tags/

Most are due to the base image being used.  We may want to consider upgrading the ubuntu version.  If we do this, hdfview will have to be removed.  This should be fine, since the GATK now packages this dependency.  Not sure about the effect on R.

**Comment by LeeTL1220** [comment]
Upgrading the ubuntu will not eliminate all vulnerabilities.

**Comment by LeeTL1220** [comment]
``emacs`` makes this image much larger

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2897](https://github.com/broadinstitute/gatk/issues/2897) via [**ZenHub**](https://www.zenhub.com/)
