### ISSUE TITLE
WDL fails in cromwell local backend using docker

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#719]
Case CNV+ACNV workflow WDL works fine in :  
- JES (+ docker)
- Local backend without docker

Unfortunately, the creation of symlinks in the WholeGenomeCoverage task will fail in local backends that use docker, since the docker path will be used to generate the symlink.

Proposed solution:
- Roll the WGS SparkGenomeReadCounts and the CalculateTargetCoverage into one WDL task and decide on the outputs that way.  Use an if ${isWGS} in there.
- [ ] Done for Case workflow.
- [ ] Done for PoN creation workflow.
- [ ] Implement test (if possible) in travis to run cromwell+local backend+docker.
- Automated tests for JES are implemented as part of automated evaluations in jenkins.
- Automated tests for local without docker are implemented in travis in this repo.

**Comment by samuelklee** [comment]
See #983 and #961.
