### ISSUE TITLE
Include the possibility of higher order amplification events in the germline CNV caller

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#721]
Here's an example. Blue dots shows the log likelihood for a het dup event. Had we included a hom dup state, we would get an event. They are not very rare in germline. We must extend the states of the germline HMM to [0.5, 1.0, 1.5, 2.0, 2.5, ...].
![dup](https://cloud.githubusercontent.com/assets/15305869/18863981/0a7d5eb4-8462-11e6-8296-4d79d47128ce.png)

**Comment by mbabadi** [comment]
@davidbenjamin @samuelklee

**Comment by davidbenjamin** [comment]
Yes, definitely.  The tri-state model is an artifact of XHMM's hokey Z-scores.  I object mildly to the title of this issue, however, since hom dup presupposes phasing, which we don't do, e.g. maternal copy number = 1, paternal copy number 3 is not a hom dup.

**Comment by mbabadi** [comment]
I agree, title fixed ;-)

**Comment by mbabadi** [comment]
I agree, the title is fixed :-)

**Comment by mbabadi** [comment]
This issue is addressed is PR #857.
