### ISSUE TITLE
Should we filter reads before assembly?

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#723]
HaplotypeCaller and Mutect filter reads (due to length < 10 or mapping quality < 20 or unmapped mate or mate on different contig) after assembly.  This seems odd.  Why would we assemble reads we don't trust?

**Comment by ldgauthier** [comment]
I suspect this was to preserve sensitivity, especially for M2.  It helps to have more variation in the read position of the variant in case the variant ends up on a dangling tail off of a dangling tail or getting pruned, etc.  Running the evals with and without will tell definitively.

**Comment by takutosato** [comment]
@davidbenjamin I would like to look into this once we have the dream challenge WDL working. I think it'd be a good way for me to learn the code.

**Comment by davidbenjamin** [comment]
@takutosato This would very useful.  We don't understand how assembly interacts with M2 and this is a great place to start.

**Comment by takutosato** [comment]
Note to self: also compare with and without -RF NonZeroReferenceLengthAlignmentReadFilter flag

**Comment by davidbenjamin** [comment]
We're freeing Takuto's time for work on his new strand bias model.
