### ISSUE TITLE
Plotting (CNV and ACNV) should use the reference to determine regions of the genome to plot

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#726]
In the current state we have two issues:
- we only support hg19/b37
- For demos and testing we often use truncated references (e.g. chr20 for workshops).  The plotting generates a mostly-blank genome as a result...

![sm-74p4m_before_after_cr_lim_4](https://cloud.githubusercontent.com/assets/2152339/18967409/1e337e50-8653-11e6-9e9c-6188e91a715a.png)

**Comment by samuelklee** [comment]
Dupe of #686.
