### ISSUE TITLE
If PoN QC removes all samples and the number of input samples is small, should we automatically disable the QC?

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#729]
On a small corpus of samples, it seems the that the PoN QC is quite aggressive and will remove all samples.  Can we have it automatically bypass the QC step?

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2899](https://github.com/broadinstitute/gatk/issues/2899) via [**ZenHub**](https://www.zenhub.com/)
