### ISSUE TITLE
``CombineReadCounts`` should allow duplicate sample names

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#732]
Rename the columns to *_1, *_2, etc.

The allowing of renaming should be a flag that goes into `CombineReadCounts` and default duplicate sample names should be disallowed.
I.e....
`--allow-multiple-replicates` default to false...

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2900](https://github.com/broadinstitute/gatk/issues/2900) via [**ZenHub**](https://www.zenhub.com/)
