### ISSUE TITLE
Emit all alleles in Mutect

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#733]
We should emit _all_ alleles with their posterior probabilities or somatic qual scores or whatever.  This will make it easier to unite all filtering in a second post-processing step.

**Comment by davidbenjamin** [comment]
Shortly after posting this issue, Sarah Calvo pointed out to us that this is an outright bug as far as her work on somatic variants in mitochondria is concerned.

**Comment by chandrans** [comment]
Hey David. What do you mean by "all alleles" You mean like any potential allele that is at the position? Like is a GVCF? Thanks!

**Comment by davidbenjamin** [comment]
Hi Sheila, we weren't thinking as permissive as a gvcf, more like a vcf, i.e. we will emit all alleles that we believe actually exist as somatic mutations.  This will only affect a small number of sites.

**Comment by chandrans** [comment]
Okay got it. Thanks. Hopefully users will be happy with this! We have had some complaints about it not being permissive enough especially at messy sites.

**Comment by davidbenjamin** [comment]
@chandrans It's good to hear that (the complaints, that is).  Are these complaints on the forum?

**Comment by chandrans** [comment]
@davidbenjamin Yes, from the forum. I have been emailing Takuto with some interesting MuTect2 issues/comments from users. Would you like to be in on these threads?

**Comment by davidbenjamin** [comment]
@chandrans yes please!

**Comment by chandrans** [comment]
Awesome. Thanks David. Will do.

**Comment by davidbenjamin** [comment]
Closed by #816.
