### ISSUE TITLE
Funny .class version conflict from the gatk public dependency.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#738]
I'm getting this exception when running GenotypeGVCFs from gatk-protected.jar:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.broadinstitute.hellbender.utils.Dirichlet.log10MeanWeights()[D
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AlleleFrequencyCalculator.getLog10PNonRef(AlleleFrequencyCalculator.java:82)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:246)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:201)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.regenotypeVC(GenotypeGVCFs.java:162)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:145)

```

For the record I have run ```gradle clean``` before ```gradle record``` and also remove the maven and gradle caches (```~/.m2``` and ```~/.gradle```) to make sure is not due to a rogue .jar file.

Gatk-protected's public depenency is set to ```org.broadinstitute:gatk:4.alpha.2-61-gcdc484c-20160929.184342-1```

That method ```public double[] log10MeanWeights()``` is present in ```cdc484``` but if I run ```javap -cp gatk-protected.jar org.broadinstitute.hellbender.utils.Dirichlet``` I get the following:
```
Compiled from "Dirichlet.java"
public class org.broadinstitute.hellbender.utils.Dirichlet {
  public org.broadinstitute.hellbender.utils.Dirichlet(double[]);
  public org.broadinstitute.hellbender.utils.Dirichlet(org.broadinstitute.hellbender.utils.Dirichlet, double[]);
  public static org.broadinstitute.hellbender.utils.Dirichlet symmetricDirichlet(int, double);
  public double[] effectiveMultinomialWeights();
  public int size();
}
``` 

It seems this is due to the present of a Dirichlet.java in gatk-protected that masks the gatk public class.

**Comment by droazen** [comment]
`It seems this is due to the present of a Dirichlet.java in gatk-protected that masks the gatk public class.`

Can the protected version of the class be removed or renamed? Should it be merged with the public version?

**Comment by davidbenjamin** [comment]
@droazen The protected version is a subset of the public version and can be removed.  Would you like me to issue a PR doing this?

**Comment by vruano** [comment]
The authors of depending classes should have the last word, but since is at least partly in public I think it should all be there.

**Comment by vruano** [comment]
@davidbenjamin that is totally true, at least there is a missing constructor in the public taking ```(Dirichlet, double[])``` arguments. Effectively is adding up the first dirichlet (prior) alphas to the counts to get an updated set of alphas.

**Comment by vruano** [comment]
Also it is this passing the test... if it is, this is hinting that there may be something to be fixed in the jar build process as we want this things to fail early.

**Comment by davidbenjamin** [comment]
I'm the author of the only depending classes.  The fix was trivial and I'll issue a PR shortly.
