### ISSUE TITLE
When upgrading Firehose to the next version of GATK for CNV toolchain, make sure to change the CNLoH task to call the correct CLI

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#742]
Should now be `CallAllelicSplits`

Rename the task configuration as well.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2903](https://github.com/broadinstitute/gatk/issues/2903) via [**ZenHub**](https://www.zenhub.com/)
