### ISSUE TITLE
Update forum posts for the name change in CNLoH caller

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#743]
Now called `CallAllelicSplits` 

This should happen after (or right before) the next release.
- [ ] Update forum posts
- [ ] Add forum post explaining the output of the cnb_called files

See issue #585

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2904](https://github.com/broadinstitute/gatk/issues/2904) via [**ZenHub**](https://www.zenhub.com/)
