### ISSUE TITLE
Standardize gCNV PoN output

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#745]
The PoN must:

- [x] Contain as much non-trivial information as possible:
    \* Model parameters (W, \Psi, m; also, ordered norms of W)
    \* Sample names used to make the PoN
    \* Posterior expectations (\gamma, z, d, total remove variance, total unexplained variance)
    \* Useful distributions (bootstrapped distribution of log likelihoods and sample-specific variances)
    \* Command-line used to make the PoN (add a log file to the HDF5 bundle in the end)

- [x] Be human-readable ideally. Binary dumps are fast but are difficult to work with in debugging.
- [ ] Encapsulated and easily shared, perhaps via HDF5 bundles

**Comment by mbabadi** [comment]
This is partially addressed in PR #857. We must, however, decide whether or not we want to bundle models into HDF5 blobs.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2905](https://github.com/broadinstitute/gatk/issues/2905) via [**ZenHub**](https://www.zenhub.com/)
