### ISSUE TITLE
Evaluate gCNV for rare germline CNV events

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#747]
We use Genome STRiP TCGA/GPC2 call sets as ground truth.

It is desirable to evaluate:

(1) XHMM and CODEX vs. GATK (almost done @asmirnov239)
(2) GATK ROC curves as a function of bias latent space dimension D
(3) GATK ROC curves for a fixed D, and for different unexplained variance models: (isotropic, target-resolved, adaptive), w/ and wo/ sample-specific unexplained variance calling during PoN creations, and calling. That is, 3 x 2 x 2 = 12 cases.

**Comment by mbabadi** [comment]
This was done a while ago. Keeping open for upcoming evaluations.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2907](https://github.com/broadinstitute/gatk/issues/2907) via [**ZenHub**](https://www.zenhub.com/)
