### ISSUE TITLE
ACNV WGS Failures without error message (RAM?)

### ISSUE THREAD

**Issue by achevali** [broadinstitute/gatk-protected#762]
/dsde/working/aaronc/testing/LUAD/wgs/acnv/TCGA-50-5066-01A-01D-1625-08-sim-final.seg.out
/dsde/working/aaronc/testing/LUAD/wgs/acnv/TCGA-44-2666-01A-01D-0969-08-sim-final.seg.out

**Comment by samuelklee** [comment]
No action if a RAM issue, closing.
