### ISSUE TITLE
Update do spark 2.0

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk-protected#763]
Update to the current version of public.  This requires an update to spark 2.0 which means it needs some extra testing before merging.  

@LeeTL1220 would like to run some wdl's to check that things are still working.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2911](https://github.com/broadinstitute/gatk/issues/2911) via [**ZenHub**](https://www.zenhub.com/)
