### ISSUE TITLE
M2 Code Refactoring

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#767]
@kcibul commented on [Fri Mar 13 2015](https://github.com/broadinstitute/gsa-unstable/issues/876)

The comments are from the initial pull request for M2 from Eric Banks.  He agreed we should go ahead with the merge, since it will allow others to work off master rather than my branch and the vast majority of the code is under private and isolated.  
1. Move BaseQualitySumPerAlleleBySample into the annotator package to be like the rest of the VariantAnnotations
2. Recommendation: push M2 initialization into a common initializer function/class used by both this and the haplotype caller. Then we don't need to have 2 copies of all this code but you also don't need to directly inherit from HC (which I see why you might not want to do).
3. [Referring to calcGenotypeLikelihoodsOfRefVsAny] EB: I feel like this is the same model that is used in the HC, but with the (undocumented) parameter f. Isn't germline just a specific case where f=1.0? Because if so, I'm a really big fan of not duplicating the hard math.
4. [Referring to findReadByName] EB: Seems like a useful public static method. I can't believe we didn't implement this somewhere else. In any case, not a huge deal.
5. [Referring to M2 arguments] EB: All of these arguments should go into an ArgumentCollection that is shared by both this and HC.
6. Generally speaking, a lot of shared code should either go into an abstract superclass that both HC and M2 inherit from, or into a shared utility type class they both invoke.
7. [Referring to how_to_make_dream3_bams.txt]: EB: Not sure where to put txt files, but I think this path is expressly for java files. KC: agreed, the text of this could go into the Javadoc for the test itself

---

@eitanbanks commented on [Tue May 19 2015](https://github.com/broadinstitute/gsa-unstable/issues/876#issuecomment-103490913)

In general, our best practices specify that the 'final' keyword should be used whenever the hell is can be.  We've had issues in the past where this has caught bugs.

But the most important piece (which I think is covered above) is to minimize as much as absolutely possible the duplication of code.

---

@ldgauthier commented on [Tue Jun 02 2015](https://github.com/broadinstitute/gsa-unstable/issues/876#issuecomment-107968052)

There are a couple of bugs related to item 1 (above) that some annotation refactoring could fix.

Bugs:
- Right now BaseQualitySumPerAlleleBySample is in the Standard set and throws exceptions when UG is run using the internal jar (tests are passing apparently because that code is still in private?)
- If a user (namely me) specifies a new annotation, AD gets thrown out unless explicitly specified

Refactoring fixes:
- Maybe create an annotation group (interface) called Standard_M2 (StandardM2Annotation.java)
- Move "DepthPerAlleleBySample", "BaseQualitySumPerAlleleBySample", "TandemRepeatAnnotator", OxoGReadCounts (when it's done) to Standard_M2
- Probably should make BaseQualitySumPerAlleleBySample error gracefully if called from UG anyway (there are a lot of great examples in Ron's work on other annotations, see SpanningDeletions.java)

---

@ldgauthier commented on [Wed Jul 08 2015](https://github.com/broadinstitute/gsa-unstable/issues/876#issuecomment-119558747)

For private/gatk-queue-extensions-internal/src/main/qscripts/org/broadinstitute/gatk/queue/qscripts/dev/Qscript_M2_normalNormalLoop.scala:
- possibly rename since it's used to run tumors and normals or extend run_M2_ICE_NN.scala so that it takes contamination fraction estimate
- change the scala class name from "Qscript_VariantAnnotator"

---

@ldgauthier commented on [Fri Jul 24 2015](https://github.com/broadinstitute/gsa-unstable/issues/876#issuecomment-124635546)

In M2.java around line 1104, move downsampling parameters (maxReadsInRegionPerSample and minReadsPerAlignmentStart) from hard-coded consts to arguments

---

@vdauwera commented on [Fri Dec 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/876#issuecomment-165905522)

@ldgauthier @kcibul  Was this done when M2 was ported or is it still TODO?

---

@ldgauthier commented on [Fri Dec 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/876#issuecomment-165905839)

Still TODO.  By whom, I have no idea...  Not it!

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/876#issuecomment-260458017)

Moving this to GATK; @davidbenjamin can feel free to use these observations or close the ticket if it's no longer applicable.

**Comment by davidbenjamin** [comment]
These are all either: i) already done by @takutosato and me; ii) automatically mooted by the GATK4 port; or iii) fixed earlier by others.
