### ISSUE TITLE
M2 normal-normal calling is dependent on sample name

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#768]
@ldgauthier commented on [Wed Mar 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/884)

M2 uses lots of handy GATK sample-name based utilities, so if you pass in two bams with the same sample name, all of the variants are present in the normal.

I think the root of this issue is in SomaticGenotypingEngine::callMutations() at line 212/213 where we subset the readLikelihoods by sample name. (This should be refactored anyway because is uses the old PerReadAlleleLikelihoodMap)

---

@vdauwera commented on [Wed Mar 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/884#issuecomment-83050157)

#831 proposes to refactor all instances of PerReadAlleleLikelihoodMap. Only hasn't been done yet because we lack of clear example of what that entails (what should it be replaced by exactly?). There's a beer in it for you if you provide such an example. 

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/884#issuecomment-260459360)

Moving to GATK4. @davidbenjamin, up to you to determine whether this is still applicable.

**Comment by davidbenjamin** [comment]
No longer relevant.  We do have some issues with sample names but the hellbender engine team are going to sort that out with tagged arguments.
