### ISSUE TITLE
M2 VCF -> Oncotator -> MAF

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#769]
@kcibul commented on [Tue May 19 2015](https://github.com/broadinstitute/gsa-unstable/issues/992)

Currently, there are some disconnects between how Oncotator handles VCFs.  These could be configuration problems or required new functionality.  However, the goal is to be able to create a pipeline (which will have to go into FH in a separate ticket) that takes as input an M2-VCF and outputs a MAF with the following characteristics:
1.  M2 VCFs are single tumor-normal pair -> the MAF should have 1 row for each variant (the normal should not have it's own row)
2. The real test is to make sure the methods downstream of Oncotator (OxoG, MutSig) can run on these MAFs.  

At a minimum, the following fields need to make it out:

AF (format) -> tumor_f  
0 -> init_t_lod (we can forgo this and see what explodes if anything downstream)
TLOD -> t_lod_fstar 
AD for tumor alt -> t_alt_count 
AD for tumor ref -> t_ref_count 
filter -> judgement

_new_ OxoG related (see #991)
i_t_ALT_F1R2
i_t_ALT_F2R1
i_t_REF_F1R2
i_t_REF_F2R1

---

@kcibul commented on [Wed Jul 01 2015](https://github.com/broadinstitute/gsa-unstable/issues/992#issuecomment-117825595)

on the final step after OxoG (inferring ONPs from Oncotator)

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/992#issuecomment-260460906)

This belongs to GATK4 now.

**Comment by davidbenjamin** [comment]
Oncotator will be rewritten in GATK4.
