### ISSUE TITLE
M2 should support multiple PON inputs

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#770]
@kcibul commented on [Fri May 29 2015](https://github.com/broadinstitute/gsa-unstable/issues/1004)

and the check (ie presence in panel) should pass if any of the PONs have a hit.

This may already work, we need to verify

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1004#issuecomment-260461634)

This belongs to GATK4 now.

**Comment by davidbenjamin** [comment]
This might not fit into how we use the PoN in the future.  We can re-open depending on how we design things.
