### ISSUE TITLE
M2 clustered_events filter is throwing out real DLBCL mutations

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#773]
@ldgauthier commented on [Thu Jul 23 2015](https://github.com/broadinstitute/gsa-unstable/issues/1074)

Chip has been comparing M1 and M2 calls for DLBCL samples and some of the M1 calls in which he places a lot of confidence are being filtered out by M2.  (see example below, slightly modified from his commandline) The TP variant is being filtered out because it is adjacent to another variant ("clustered"), but that variant fails the TLOD threshold and is filtered for other reasons. Chip says some tumor types just have real clustered variants, so while this is a cool thing we can determine from the assembly, I'm not sure that using it as a filter is the right thing to do. If I do a quick calculation of the NA12878 normal-normal benchmarks after adding back in variants that are only filtered by clustered_events, we would gain 10 SNPs and 3 indels across all the normal-normal comparisons, which represents a 10% increase in SNPs and ~20% increase in indels.

In order to get the normal-normal FP numbers back down, I'm going to try adding in some form of strand bias and read position filters (either M1-style or hard filters on HC-style annotations), since they were present in M1 but haven't been implemented in M2 yet.

```
java -jar $GATKjar -T M2 -L 3:38182183-38183097 \
-I:normal  /seq/picard_aggregation/C593/916201593/v3/916201593.bam  \
-I:tumor  /seq/picard_aggregation/C593/1102500148/v3/1102500148.bam  \
--reference_sequence /seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta \
--dbsnp /xchip/cga/home/kcibul/analysis/dream/mutect_ref/dbsnp_138.b37.vcf \
--cosmic /xchip/cga/reference/hg19/hg19_cosmic_v54_120711.vcf --out DLBCL-Ls1583-Tumor.vcf \
--normal_panel /cga/tcga-gsc/mutect/panel_of_normals/panel_of_normals_m2_paad/agilent_hg19_m2_paad_149_normal_panel.vcf \
--bamOutput DLBCL-Ls1583-Tumor_M2.bam
```

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1074#issuecomment-260465980)

Moving to GATK4 to @davidbenjamin's attention. Feel free to close if this is not useful/applicable anymore.

**Comment by davidbenjamin** [comment]
This is part of a broader issue of replacing hard filters with a probabilistic model, but it's useful to keep up as an example.

**Comment by davidbenjamin** [comment]
Throwing away this filter.

**Comment by MurphyDavid** [comment]
I'm using v3.8-0-ge9d806836 but I've still seeing apparently-real variants being filtered as "clustered_events".

It looks like "clustered_read_position" was cut out but "clustered_events" is still there unless I'm reading it wrongly (entirely possible).

**Comment by davidbenjamin** [comment]
@MurphyDavid Try Mutect2 in GATK 4.  We never backported these and other changes to GATK 3.

**Comment by MurphyDavid** [comment]
Should the change be in FilterMutectCalls? (I see filtering has been separated from Mutect2 testing with v4 beta 5)

I seem to be getting the same clustered_events filters in my output VCF as when using v3.8-0 

should I open an new issue on the beta project for this or is the clustered_events filter still supposed to be included by default?

`2416	.	T	C	.	clustered_events`

**Comment by davidbenjamin** [comment]
The GATK clustered events filter removes variants coming from a reassembled haplotype that had too many other variants, which is a proxy for mapping artifacts.  This is set by the `maxEventsInHaplotype` argument.  By default it is 2, that is, variants on haplotypes with one other variant are not filtered.  You could increase this to regain sensitivity, but beware that mapping artifacts can look a lot like real variants.

PS We are working on ways to filter mapping artifacts without resorting to hard filters like this one, which we acknowledge hurt sensitivity.

**Comment by MurphyDavid** [comment]
Thanks for the quick reply! slightly upping maxEventsInHaplotype  seems to sort it out in most cases.

**Comment by annaquaglieri16** [comment]
Hi there, 

I have a set of calls made with GATK3 and a lot of variants for which I have a good confidence they are true positives are filtered out as clustered events. I have two questions about it:

1) Shall I just use GATK4 at this stage because this filter was updated on gatk4 but not on gatk3
2) I am confused about the definition of such filter. In this thread @davidbenjamin states that "The GATK clustered events filter removes variants coming from a reassembled haplotype that had too many other variants," but from the mutect papers it defines the clutered positions filter as "Reject false positives caused by misalignments hallmarked
by the alternate alleles being clustered at a
consistent distance from the start or end of the read
alignment." which is a different matter. 

Which definition is actually applied?

Thanks, 
Anna
