### ISSUE TITLE
MutSig and FPs in TCGA Bladder (N = 245)

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#774]
@marawr commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023)

Run MutSig for M2 on TCGA Bladder with a sample size of 245. Check for new FP phenotypes. 

---

@marawr commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113199915)

Based on the TCGA Bladder cohort, it looks like we are still seeing an inflation of 3bp deletions in repetitive contexts. The counts of INS / DEL / SNPs is shown below:
 
![image](https://cloud.githubusercontent.com/assets/4805442/8233773/07e320b6-15a6-11e5-8f12-6e107eabc4a1.png)

With the following length distribution for deletions: (Distributed evenly across patients)
![image](https://cloud.githubusercontent.com/assets/4805442/8235572/b78e2146-15b0-11e5-9efa-5c60fc3e3bea.png)

An example is:
![image](https://cloud.githubusercontent.com/assets/4805442/8235580/c42c9ff4-15b0-11e5-82a5-c7967dd0c9d1.png)

via the command: 
java -Xmx4g -cp /xchip/tcga/gdac_prod/applications/process_mgmt/firehose_task_registry/cga/M2_scatter/broadinstitute.org/cancer.genome.analysis/10882/22//gatk-package-internal-3.4-SNAPSHOT.jar org.broadinstitute.gatk.engine.CommandLineGATK -T M2 -L  1:20809955-20809965  -I:normal /seq/picard_aggregation/C500/TCGA-BL-A0C8-10A-01D-A10S-08/v5/TCGA-BL-A0C8-10A-01D-A10S-08.bam -I:tumor /seq/picard_aggregation/C500/TCGA-BL-A0C8-01A-11D-A10S-08/v6/TCGA-BL-A0C8-01A-11D-A10S-08.bam --reference_sequence /seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta --dbsnp /xchip/cga/home/kcibul/analysis/dream/mutect_ref/dbsnp_138.b37.vcf --cosmic /xchip/cga/reference/hg19/hg19_cosmic_v54_120711.vcf --out LUAD-TCGA-05-4249-TP-NB-SM-1OIMZ-SM-1OINA_1.vcf --normal_panel /cga/tcga-gsc/mutect/panel_of_normals/panel_of_normals_m2_paad/agilent_hg19_m2_paad_149_normal_panel.vcf 

This issue leads to a list of over a few hundred significant genes, driven by those deletions, so I'll remove those for searching other FP types. 

---

@akiezun commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113202179)

are they in frame deletions or frame shifts? If they are FPs they should not be enriched for in-frames. If they are real events, there should be many more in-frames than expected by chance. 

---

@marawr commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113204548)

There are many more in-frame deletions. I think they are real in the DNA from a sequencing perspective, but not from a biology of the cancer perspective. Our tools have just become too sensitive and catch potential lab artifacts :). 

![image](https://cloud.githubusercontent.com/assets/4805442/8235874/9745b80c-15b2-11e5-9be4-e124baacb949.png)

To note: we should triple check this by running on the latest build that you guys have I think in case we (firehose) is out of sync. 

---

@kcibul commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113208422)

First of all -- this is awesome info, thank you!

Can you send along a pointer to one of the output VCFs?  I can tell from that if it's got the latest M2.  Sure seems like it's not!

---

@marawr commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113221384)

Hey Kris,

Here's an example of one of the raw VCFs: /xchip/cga_home/jhess/M2_calls_for_Mara/PanCan_Broad_TCGA_Bladder_Hybrid_Selection/TCGA-DK-A1AB.vcf

The full build is from: /xchip/tcga/gdac_prod/applications/process_mgmt/firehose_task_registry/cga/M2_scatter/broadinstitute.org/cancer.genome.analysis/10882/22//gatk-package-internal-3.4-SNAPSHOT.jar 

Thanks!!
Mara

---

@ldgauthier commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113226606)

The VCF header doesn't have the str_contraction filter listed. The version used is also from April and the STR filter didn't go in until May. I'm guessing a lot of those should be caught by the new filter if the latest version is run.

---

@marawr commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113231824)

Awesome to hear that this is probably just version issues! Where would the
latest build live? I can test it on one of these sites if you want and
update firehose too if all goes well.  (An example site is above too.)

Thanks,
Mara

On Thu, Jun 18, 2015 at 1:25 PM, ldgauthier <notifications@github.com>
wrote:

> The VCF header doesn't have the str_contraction filter listed. The version
> used is also from April and the STR filter didn't go in until May. I'm
> guessing a lot of those should be caught by the new filter if the latest
> version is run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113226606>
> .
>

-- 
Mara Rosenberg
Associate Computational Biologist
Broad Institute of MIT & Harvard
415 Main Street
Cambridge, MA 02142
(617)-714-8328

---

@ldgauthier commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113234057)

The latest nightly build is always here: /humgen/gsa-hpprojects/GATK/private_unstable_builds/GenomeAnalysisTK_latest_unstable.jar, which right now points to /humgen/gsa-hpprojects/GATK/private_unstable_builds/GenomeAnalysisTK-3.4-33-g9cd2cd4/GenomeAnalysisTK.jar.  That version should also have the oxoG annotations and contamination adjustment.

---

@kcibul commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113234110)

perfect -- I'll get you a new build to test out.  we're currently working
on updating the firehose one also

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org
617-714-7637

On Thu, Jun 18, 2015 at 1:39 PM, Mara Rosenberg <notifications@github.com>
wrote:

> Awesome to hear that this is probably just version issues! Where would the
> latest build live? I can test it on one of these sites if you want and
> update firehose too if all goes well. (An example site is above too.)
>
> Thanks,
> Mara
>
> On Thu, Jun 18, 2015 at 1:25 PM, ldgauthier <notifications@github.com>
> wrote:
>
>
> > The VCF header doesn't have the str_contraction filter listed. The
> version
> > used is also from April and the STR filter didn't go in until May. I'm
> > guessing a lot of those should be caught by the new filter if the latest
> > version is run.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113226606
> >
> > .
> >
>
>
>
> --
> Mara Rosenberg
> Associate Computational Biologist
> Broad Institute of MIT & Harvard
> 415 Main Street
> Cambridge, MA 02142
> (617)-714-8328
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113231824>
> .
>

---

@kcibul commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113234197)

What she said ;)

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org
617-714-7637

On Thu, Jun 18, 2015 at 1:47 PM, ldgauthier <notifications@github.com>
wrote:

> The latest nightly build is always here:
> /humgen/gsa-hpprojects/GATK/private_unstable_builds/GenomeAnalysisTK_latest_unstable.jar,
> which right now points to
> /humgen/gsa-hpprojects/GATK/private_unstable_builds/GenomeAnalysisTK-3.4-33-g9cd2cd4/GenomeAnalysisTK.jar.
> That version should also have the oxoG annotations and contamination
> adjustment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113234057>
> .
>

---

@marawr commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113237202)

Success!! Thank you!

![image](https://cloud.githubusercontent.com/assets/4805442/8238055/541b2346-15c1-11e5-8fe3-20c201a5dc6e.png)

For the interim then, I'll put that jar as part of the hacked firehose workflow if that's okay to run on a few hundred samples (and redo MutSig). 

---

@kcibul commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113237550)

That would be perfect -- thanks!

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org
617-714-7637

On Thu, Jun 18, 2015 at 1:55 PM, Mara Rosenberg <notifications@github.com>
wrote:

> Success!! Thank you!
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/4805442/8238055/541b2346-15c1-11e5-8fe3-20c201a5dc6e.png>
>
> For the interim then, I'll put that jar as part of the hacked firehose
> workflow if that's okay to run on a few hundred samples (and redo MutSig).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113237202>
> .
>

---

@marawr commented on [Thu Jun 18 2015](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-113241110)

cool - done. 
Firehose module M2_scatter is at v23 now in workspace: Algorithms. 

(Will get back to you on the MutSig list when all those samples process through.)

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1023#issuecomment-260462332)

Moved to GATK4 repo to @davidbenjamin's attention; feel free to close if unwanted.

**Comment by davidbenjamin** [comment]
Seems like this was closed earlier.  But ultimately I think @vruano's STR likelihoods model is going to make an STR hard filter obsolete.
