### ISSUE TITLE
M2 contamination handling not equivalent to M1

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#776]
@ldgauthier commented on [Mon Dec 07 2015](https://github.com/broadinstitute/gsa-unstable/issues/1252)

Chip plotted the M1 and M2 calls using number of alternate reads vs. depth*contamination:
![image](https://cloud.githubusercontent.com/assets/6578548/11639869/617569fc-9cfd-11e5-9806-48830e6ea1e5.png)

It looks like M2 contamination downsampling isn't doing the same thing as M1.  Chip ran these data with Genome Analysis Toolkit (GATK) v3.4-45-g6e00632, Compiled 2015/07/07 19:13:53. 

More info from Chip for testing:
 The tumor/normal pair with the largest problem of calls below the contamination level (3.7%) was DLBCl-Ls3085: 

DLBCL-Ls3085-Tumor
/seq/picard_aggregation/C593/1102503033/v3/1102503033.bam

DLBCL-Ls3085-Normal
/seq/picard_aggregation/C593/1102800748/v3/1102800748.bam

DLBCL-c_D_pair13 was shown as an example with long deletions that showed up in the M2 bams.  The link that Mark prepared 

http://iwww.broadinstitute.org/igvdata/humgen/gsa-hpprojects/dev/fleharty/VariantReviewLunch/Nov-12-2015/m2.xml

has the vcf, the combined M2 bam, the M2 bam split into tumor and normal samples, and the original bwa bams.  If we navigate to X:119,059,043-119,059,506, we should see something like this : 
![image](https://cloud.githubusercontent.com/assets/6578548/11639902/9dd2c322-9cfd-11e5-92e0-ad593e02da42.png)
panel 1: vcf
panel 2: normal M2 bam
panel 3: tumor M2 bam
panel 4: combined tumor+normal+HC bam
panel 5: bwa tumor bam
panel 6: bwa normal bam

I've turned on color by tag, selecting "HC" for this screenshot (not sure if your IGV comes up that way by default). 
The HC tag pattern is that the sample=HC reads all have HC tags and the reads with sample =c_D_pair_13_Dx or sample=RICOVER_134_N do not have HC tags.  Is this consistent with what you find?  Is this consistent with the most recent M2 version? 

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1252#issuecomment-260475931)

Moving to GATK4 for @davidbenjamin's to determine its fate.

**Comment by davidbenjamin** [comment]
Hmmm, can't make a snap judgment.  Leaving this for now.

**Comment by davidbenjamin** [comment]
Upon investigation, neither one downsamples correctly.
