### ISSUE TITLE
MuTect2 passing variants seen in germline

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#778]
@chandrans commented on [Tue Jul 12 2016](https://github.com/broadinstitute/gsa-unstable/issues/1434)

### Affected tool(s)

MuTect2
### Affected version(s)

3.6
### Description

A user has reported seeing PASS variants from MuTect2 that have a high frequency in the germline sample. For example:
`#CHROM POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  TUMOR   NORMAL
6   32610186    .   G   GATTTATTAAAAAAC .   PASS    ECNT=1;HCNT=2;MAX_ED=.;MIN_ED=.;NLOD=28.90;TLOD=15.79   GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1  0/1:179,22:0.066:0:0:.:5724,0:100:79    0/0:196,30:0.070:0:1:.:6194,12:105:91`
Notice the normal sample has 30 reads supporting the alternate allele, but it is called 0/0.
#### Steps to reproduce

Test files and commands in thread below.
#### Expected behavior

Either the variant should FAIL or not be emitted at all.

This Issue was generated from your [forums](http://gatkforums.broadinstitute.org/gatk/discussion/comment/30667#Comment_30667) 

---

@chandrans commented on [Tue Jul 12 2016](https://github.com/broadinstitute/gsa-unstable/issues/1434#issuecomment-232169418)

Test files here:
`/humgen/gsa-scr1/schandra/cooperjam_MuTect2PASSVariantsAreInNormals/GATK_error`

Command I ran:
`java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T MuTect2 -R /humgen/gsa-hpprojects/GATK/bundle/2.8/b37/human_g1k_v37.fasta -I:normal /humgen/gsa-scr1/schandra/cooperjam_MuTect2PASSVariantsAreInNormals/GATK_error/AMUM.normal.subset.bam -I:tumor /humgen/gsa-scr1/schandra/cooperjam_MuTect2PASSVariantsAreInNormals/GATK_error/AMUM.post.subset.bam -o Sheila.MuTect2.vcf -bamout Sheila.MuTect2.bam -L 6:32609886-32610486 -L 7:15725829-15726429 -L 8:75944109-75944709`

---

@ldgauthier commented on [Wed Jul 13 2016](https://github.com/broadinstitute/gsa-unstable/issues/1434#issuecomment-232340818)

I would expect this to get filtered by the ALT_ALLELE_IN_NORMAL filter, but it appears that that filter has stricter rules than I expected.  By default, it will filter sites with (more than one alt read seen in the normal OR more than 0.03 allele fraction in normal) AND the alt quality score sum in the normal more than 20.  Here the QSS isn't coming out right (@chandrans -- can you make another ticket for that?  It should be a single integer, but here it's a list), but the normal alt QSS appears to be 12, which is less than 20.  So those alt reads in the normal are of very dubious quality.  Honestly, I'm not entirely sure how we calculate the QSS for indels.  It makes a lot more sense for SNPs where we use base quality.  @takutosato can you look into how QSS is calculated for indels when you get a chance?

---

@chandrans commented on [Wed Jul 13 2016](https://github.com/broadinstitute/gsa-unstable/issues/1434#issuecomment-232387215)

Takuto, you may also take a look at the BAM and bamout because I don't know how the call is being made. Here is the normal sample at the site (bamout):
<img width="1440" alt="screen shot 2016-07-13 at 11 11 34 am" src="https://cloud.githubusercontent.com/assets/6998669/16808452/93d5e202-48ea-11e6-8eb1-d032241b318b.png">

The tumor sample at the site:
<img width="1440" alt="screen shot 2016-07-13 at 11 12 20 am" src="https://cloud.githubusercontent.com/assets/6998669/16808482/ad95d0a8-48ea-11e6-9514-48c6187706bb.png">

Artificial Haplotypes:
<img width="1440" alt="screen shot 2016-07-13 at 11 12 45 am" src="https://cloud.githubusercontent.com/assets/6998669/16808495/bc64fe06-48ea-11e6-88b1-a950bdf319fd.png">

None of the reads contain evidence for the insertion. 

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1434#issuecomment-260494940)

Moving to GATK4

**Comment by davidbenjamin** [comment]
The issue here is not that M2 filters aren't doing their job or that there's a bug in the genotyping.  Rather, as @chandrans suggests the right place to look is assembly.  It's very telling to me that the allele fractions of tumor and normal are similar, which seems to be the sign of a shared artifact.  Since sample preparation etc is usually not the same for tumor and normal it makes me wonder whether these are shared assembly artifacts.  I'll open a ticket for doing this sort of thing.
