### ISSUE TITLE
MuTect2 QSS should be output as a single integer

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#779]
@chandrans commented on [Wed Jul 13 2016](https://github.com/broadinstitute/gsa-unstable/issues/1435)

Follow up on #1434 
Note, the QSS is a list of two values, not one single integer.

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1435#issuecomment-260495050)

Moving to GATK4

**Comment by ldgauthier** [comment]
I definitely made a mistake when I commented on the old issue -- in the code we blatantly reference the second item in the array, so there has to be more than one integer.  Oops.

**Comment by chandrans** [comment]
Thanks Laura!
