### ISSUE TITLE
Allow MuTect2 users to change thresholds for determining active regions

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#780]
@chandrans commented on [Thu Aug 18 2016](https://github.com/broadinstitute/gsa-unstable/issues/1455)

### Tool(s) involved

MuTect2
### Description

Right now, users cannot set the normalLod and nonRefInNormal thresholds for determining active regions in MuTect2. The user should be allowed to set how much evidence is allowed in the normal sample vs the tumor sample before an active region is not triggered. This is a follow-up to #1449.

---

@davidbenjamin commented on [Fri Aug 26 2016](https://github.com/broadinstitute/gsa-unstable/issues/1455#issuecomment-242795473)

@chandrans FYI as of next week we are porting Mutect2 to GATK4

---

@vdauwera commented on [Fri Aug 26 2016](https://github.com/broadinstitute/gsa-unstable/issues/1455#issuecomment-242890006)

Great news!

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1455#issuecomment-260497261)

Moving this to GATK4

**Comment by davidbenjamin** [comment]
We'll keep this.  It has been suggested that M2's atrocious runtime on genomes may be due to very liberal active region determination.  It is worth adding this knob.

**Comment by davidbenjamin** [comment]
Replacing with #801.
