### ISSUE TITLE
Redundant argument in SomaticGenotypingEngine

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#781]
@davidbenjamin commented on [Wed Aug 24 2016](https://github.com/broadinstitute/gsa-unstable/issues/1461)

The first two arguments of `SomaticGenotypingEngine::callMutations` are `final List<Haplotype> haplotypes, final ReadLikelihoods<Haplotype> readLikelihoods`.  the first of these is redundant because it can be obtained as `readLikelihoods.alleles()`.

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1461#issuecomment-260497485)

Moving to GATK4 though I suspect it may already no longer be applicable.

**Comment by davidbenjamin** [comment]
We fixed this.
