### ISSUE TITLE
Create M2 Firehose Pipeline

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#782]
@kcibul commented on [Tue May 19 2015](https://github.com/broadinstitute/gsa-unstable/issues/993)

Need a Firehose pipeline for M2 VCF -> Oncotator -> OxoG -> MAF

This will include using the updated Oncotator from #992 as well as updating the OxoG pipeline to pull the new orientation bias annotation from #991 rather than calculating it off the BAMs directly

---

@ldgauthier commented on [Tue Jun 23 2015](https://github.com/broadinstitute/gsa-unstable/issues/993#issuecomment-114396386)

We will need to keep the step to split the SNP and INDEL MAFs so that the OxoG filter doesn't choke on indels.

---

@kcibul commented on [Wed Jul 01 2015](https://github.com/broadinstitute/gsa-unstable/issues/993#issuecomment-117825715)

just waiting on final step of merging in ONPs (Lee is investigating)

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/993#issuecomment-260455622)

Is it fair to say this won't get done in 3.x and can be removed from this repo's issues? 

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/993#issuecomment-260497597)

Since everything M2 has moved to GATK4, so will this.

**Comment by davidbenjamin** [comment]
According to Lee this probably won't ever need to happen.
