### ISSUE TITLE
Mutect2 does not emit FOXOG at some sites

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#783]
@chandrans commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gsa-unstable/issues/1473)

### Affected tool(s)

MuTect2
### Affected version(s)

3.6
### Description

A user reported FOXOG annotation is missing at some sites in his output VCF, but it is present at some other sites. 
#### Steps to reproduce

Test files and commands in thread below.
#### Expected behavior

FOXOG should be annotated at all sites that are applicable.
#### Actual behavior

FOXOG is not annotated at all sites that are applicable.

This Issue was generated from your [forums](http://gatkforums.broadinstitute.org/gatk/discussion/comment/32715#Comment_32715) 

---

@chandrans commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gsa-unstable/issues/1473#issuecomment-245970052)

Test files:
The user is using TCGA data. I do not have access, but Soo Hee does. She tested this out and was able to replicate the user's issue.

Command:

`java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T MuTect2 -R /humgen/gsa-scr1/schandra/hg38/hg38bundle/Homo_sapiens_assembly38.fasta -L chr3:75669000-75670000 -I:tumor 5cca592a-a346-4b63-bf58-5efc38498d2d-sliced.bam -I:normal 046b7599-214c-4ad3-b9af-f13eaba72881-sliced.bam -o test_mt2.vcf`

Note, someone with access to TCGA data will be able to access the BAM files in the command.

---

@chandrans commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gsa-unstable/issues/1473#issuecomment-245970757)

Also, Soo Hee did some in depth analysis which may be useful here: https://github.com/broadinstitute/dsde-docs/issues/1200

---

@fleharty commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gsa-unstable/issues/1473#issuecomment-245971929)

@chandrans 
In the command java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T MuTect2 -R /humgen/gsa-scr1/schandra/hg38/hg38bundle/Homo_sapiens_assembly38.fasta -L chr3:75669000-75670000 -I:tumor 5cca592a-a346-4b63-bf58-5efc38498d2d-sliced.bam -I:normal 046b7599-214c-4ad3-b9af-f13eaba72881-sliced.bam -o test_mt2.vcf

do you know what the path is 5cca592a-a346-4b63-bf58-5efc38498d2d-sliced.bam?

---

@chandrans commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gsa-unstable/issues/1473#issuecomment-245975275)

I don't have access to TCGA data, so I could not view it. Soo Hee has access and has the file. I will ask her to upload it to the server and update the path. I don't know if that is allowed though? @sooheelee  

---

@vdauwera commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gsa-unstable/issues/1473#issuecomment-245981008)

No, that's not allowed. This bug can only be taken on by someone with TCGA access. 

---

@chandrans commented on [Tue Sep 13 2016](https://github.com/broadinstitute/gsa-unstable/issues/1473#issuecomment-246754541)

Thanks Geraldine. Sorry Mark! I expect Takuto or someone on the Mutect2 team to have access to TCGA data.

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1473#issuecomment-260497897)

Moving to GATK4

**Comment by davidbenjamin** [comment]
We are implementing FOXOG from scratch in GATK4.
