### ISSUE TITLE
MuTect2 does not output default annotations when specifying -A

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#784]
@chandrans commented on [Mon Sep 12 2016](https://github.com/broadinstitute/gsa-unstable/issues/1474)

### Tool(s) involved

MuTect2
### Description

When adding -A `annotation` in MuTect2 commands, the default annotations are not output. The default annotations should still be output even when -A is used.

This Issue was generated from your [forums](http://gatkforums.broadinstitute.org/gatk/discussion/comment/32923#Comment_32923) 

---

@vdauwera commented on [Tue Sep 13 2016](https://github.com/broadinstitute/gsa-unstable/issues/1474#issuecomment-246717861)

Check with @davidbenjamin how this fits with the ported/refactored M2. I don't think any more work is warranted on M2 in GATK3.

---

@chandrans commented on [Tue Sep 13 2016](https://github.com/broadinstitute/gsa-unstable/issues/1474#issuecomment-246840384)

Oh right. So, from now on M2 requests should go in GATK4?

---

@vdauwera commented on [Tue Sep 13 2016](https://github.com/broadinstitute/gsa-unstable/issues/1474#issuecomment-246852195)

Yeah

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1474#issuecomment-260497985)

Moving to GATK4

**Comment by davidbenjamin** [comment]
We'll have to check if this is happening in GATK4.

**Comment by davidbenjamin** [comment]
I just tested this and somewhere along the line we fixed it.
