### ISSUE TITLE
Test Case: MUTECT2 detects Difficult LINE-1 insertion

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#788]
@chandrans commented on [Mon Apr 18 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348)

### Tool(s) involved

MuTect2
### Description

A user gave Congratulations because MuTect2 detected this insertion, but other callers did not. Please write a test case so MuTect2 will always detect this Line-1 insertion.
### Test Files

 /humgen/gsa-scr1/schandra/Bogdan_MuTect2DetectsInsertion/LINE1-insertion-in-TP53
### Command

`java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T MuTect2 -R /humgen/gsa-scr1/schandra/hg38/hg38bundle/Homo_sapiens_assembly38.fasta -I:normal subset_normal_TP53_chr17.7674948-7674948_SPCG-OS040_7G.GRCh38p5M.MD_intervals_hg38_male.interval_list.IR.RC.bam.bam -I:tumor subset_tumor_TP53_chr17.7674948-7674948_SPCG-OS040_8T.GRCh38p5M.MD_intervals_hg38_male.interval_list.IR.RC.bam.bam -L chr17:7674648-7675248 -o Sheila.MuTect2.vcf -bamout Sheila.MuTect2.bam`

---

@takutosato commented on [Fri Apr 29 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215830351)

This is an interesting site. I looked at it on IGV with Yossi and Chris. We think there is an insertion but we are less sure that the allele is right. It's probably a long insertion, as reads in the tumor bam show two sets of soft-clipped bases, depending on how the reads 'enter' the insertion. That is, we see both ends of the insertion as two sets of soft clipped reads but we don't observe what's in the middle. HaplotypeCaller seems to pick one end of the insertion somewhat arbitrarily and call that. We should call this insertion but I want to understand why HaplotypeCaller does what it does. Aside: the mates of reads with soft-clipped bases map to a SINE region in chromosome 19.

Two more issues about this test case:
* The evidence for the insertion comes exclusively from reverse reads. The brand new M1 strand-bias filter dutifully catches it.
* Bam-out comes out garbled and cannot be loaded in IGV.

(top: bam-out. bottom: tumor-bam)
![image](https://cloud.githubusercontent.com/assets/5185538/14924563/37712e04-0e11-11e6-90dc-540ad77fb2c9.png)

---

@takutosato commented on [Fri Apr 29 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215830558)

java command:

```
java -jar /$mygatk \
-T MuTect2 \
-R /humgen/gsa-scr1/schandra/hg38/hg38bundle/Homo_sapiens_assembly38.fasta \
-I:normal subset_normal_TP53_chr17.7674948-7674948_SPCG-OS040_7G.GRCh38p5M.MD_intervals_hg38_male.interval_list.IR.RC.bam.bam \
-I:tumor subset_tumor_TP53_chr17.7674948-7674948_SPCG-OS040_8T.GRCh38p5M.MD_intervals_hg38_male.interval_list.IR.RC.bam.bam \
-L chr17:7674648-7675248 \
-o takuto.MuTect2.vcf \
-bamout takuto.MuTect2.bam.out
```

---

@yfarjoun commented on [Fri Apr 29 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215847250)

I think that this points to interesting possible improvements to the
assembly engine...but first: several questions:

1. do the mates of reads from btoh alleles map to the same SINE on chr19?
2. do they map in a reasonable way (i.e. to the two ends of that SINE)?
3. I see some short "purple" reads at the bottom of your screenshort
(pointing to the right) what's up with those? are the soft-clipped? the
look like they might "want" to give evidence to the other strand, but for
somereason are not counted.

Thanks!!

On Fri, Apr 29, 2016 at 1:57 PM, Takuto Sato <notifications@github.com>
wrote:

> This is an interesting site. I looked at it on IGV with Yossi and Chris.
> We think there is an insertion but we are less sure that the allele is
> right. It's probably a long insertion, as reads in the tumor bam show two
> sets of soft-clipped bases, depending on how the reads 'enter' the
> insertion. That is, we see both ends of the insertion as two sets of soft
> clipped reads but we don't observe what's in the middle. HaplotypeCaller
> seems to pick one end of the insertion somewhat arbitrarily and call that.
> We should call this insertion but I want to understand why HaplotypeCaller
> does what it does. Aside: the mates of reads with soft-clipped bases map to
> a SINE region in chromosome 19.
>
> Two more issues about this test case:
>
>    - The evidence for the insertion comes exclusively from reverse reads.
>    The brand new M1 strand-bias filter dutifully catches it.
>    - Bam-out comes out garbled and cannot be loaded in IGV.
>
> (top: bam-out. bottom: tumor-bam)
> [image: image]
> <https://cloud.githubusercontent.com/assets/5185538/14924563/37712e04-0e11-11e6-90dc-540ad77fb2c9.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215830351>
>

---

@takutosato commented on [Fri Apr 29 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215857192)

We only have the coordinates of the mates because the user only gave us a subset of the bam. But the match between the SINE and our soft-clipped base is pretty good:

-- Insertion called --
TTGTGCCACTGCACTCCAGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAAAAAAAA

-- SINE -- 
hg38_rmsk_AluY range=chr19:44963314-44963624 5'pad=0 3'pad=0 strand=- repeatMasking=none
GGCTGGGTGCGGTGGCTCACACCTGTAATCGCAGCACTTTGGGAGGCCAA
GGCAGGCGGATCATGAGGTCAGGAGATAGAGACCATCCTGGCTAACACGG
TGAAACCCCATCTCTACTGAAAATACAAAAAATTAGCCAGGTGTGGTGGC
GGGTGCCTGTAGTCCCAGCTACTCGGGAGGCTGAGGCAGGAGAATGGCGT
GAACCCGGGAGGCGGAGCTTGCAGTGAGCCAAGATTGTGCCACTGCACTC
CAGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAAAAAAAAAAAATACA
TAAAATAAAAA

-- Match (using [Align Sequences Nucliotide BLAST](http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastSearch&BLAST_SPEC=blast2seq&LINK_LOC=align2seq)) --

![image](https://cloud.githubusercontent.com/assets/5185538/14927246/b2db37ee-0e1e-11e6-9a65-7e85e0e8fb1a.png)

As you can see, our called insertion exactly matches near the end of SINE. 

The other set of soft-clipped bases (the one that HaplotypeCaller decided not to call) matches exactly to the SINE too, this time near the middle. See the subject indices in the matches - the soft-clipped reads miss each other by 4 bases! 

-- The soft-clipped bases --
GTCCCAGCTACTCGGGAGGCTGAGGCAGGAGAATGGCGTGAACCCGGGAGGCGGAGCTTGCAGTGAGCCA  

-- Match --
![image](https://cloud.githubusercontent.com/assets/5185538/14927357/4ba5b314-0e1f-11e6-9168-edbfea20af75.png)

---

@takutosato commented on [Fri Apr 29 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215857969)

As for the little purple forward reads - they are hard-clipped. I agree with you @yfarjoun, I think those forward reads would've given us evidence for the insertion, and the site would not have been filtered for strand-bias.

---

@sooheelee commented on [Fri Apr 29 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215858408)

You can expect variability from person to person in where retrotransposons are. 

---

@yfarjoun commented on [Fri Apr 29 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215858871)

perhaps it makes sense to reach back to the user and ask for the
hard-clipping to be removed...hardclipping is not in our
best-practices...it might be due to incorrect application of aligner or
something like that. Would be interesting to understand what the
hard-clipping is due to, and if we would get better results if these were
soft-clipped instead.

On Fri, Apr 29, 2016 at 3:39 PM, Takuto Sato <notifications@github.com>
wrote:

> As for the little purple forward reads - they are hard-clipped. I agree
> with you @yfarjoun <https://github.com/yfarjoun>, I think those forward
> reads would've given us evidence for the insertion, and the site would not
> have been filtered for strand-bias.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215857969>
>

---

@vdauwera commented on [Fri Apr 29 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215859625)

I'll ask if we can get the original data.

---

@sooheelee commented on [Fri Apr 29 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-215864416)

If we are at the level of being able to resolve transposable elements, given the reference contains such elements, then do we need to add repeat masking to a workflow that wants to resolve these?

Here's a chart of the level of repeats in hg38: <http://www.repeatmasker.org/species/hg.html>.

---

@ldgauthier commented on [Wed May 04 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-216883384)

@takutosato I wonder where it's anchoring the one-sided insertion?  Did you try a graphOut?  They're pretty painful to sift through, but can be very informative.  You can try running again with "-graph output.dot" and open the results in [GraphViz](http://www.graphviz.org/Download.php).

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1348#issuecomment-260482441)

Hey all, is this still something you're working on/interested in, or can we close the issue? Or should we move it to GATK4?

**Comment by davidbenjamin** [comment]
We have validations now.  Let's not get bogged down with particular cases unless they teach us something.  Seems like this was just a matter of hard clipping.

**Comment by ldgauthier** [comment]
This case is nice because it's something MuTect2 can do that you can't do with a pileup-based caller on top of BWA. Although A) we didn't do a perfect job (because this isn't the SV tool) and B) I don't expect any code changes short of a dramatic assembly rewrite to break a regression test based on this case.

Although this reminds me that it's on my list to figure out what we want to do when the assembly engine detects a large SV that we know we can't call from the reads in the active region.  It would be nice to have something that says "we are confident there is an event here, but we are not confident we can call it".  Or maybe the solution is just to run the SV tool once it's ready.
