### ISSUE TITLE
Limit haplotypes in M2

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#805]
Since Mutect2 runs on a single human's worth of samples i.e. a tumor and an optional normal, we should never see more than a few haplotypes at any location.  We might therefore be able to increase speed dramatically by setting the 'maxNumHaplotypesInPopulation' argument to a smaller value than its default of 128.  The question is whether we can do this without hurting sensitivity.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2921](https://github.com/broadinstitute/gatk/issues/2921) via [**ZenHub**](https://www.zenhub.com/)
