### ISSUE TITLE
using set -x

### ISSUE THREAD

**Issue by eddiebroad** [broadinstitute/gatk-protected#817]
As a standard practice, whenever I write WDL, I have as my first command "set -x".
The command causes bash to print the commands it actually runs to stderr.
See Table 2-1 here
http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_02_03.html

@LeeTL1220 mentioned that this practice be good in the WDLs of gatk-protected so, per him, I write this issue.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2923](https://github.com/broadinstitute/gatk/issues/2923) via [**ZenHub**](https://www.zenhub.com/)
