### ISSUE TITLE
Multi-sample CNV segmentation

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#818]
Can we segment several samples at once?  For example, different single-cell samples from the same phylogeny, or samples from the same tumor at different times, will have many common CNVs.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2924](https://github.com/broadinstitute/gatk/issues/2924) via [**ZenHub**](https://www.zenhub.com/)
