### ISSUE TITLE
Filter artifacts common to tumor and normal

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#821]
If the normal has a lot of alt reads but not enough to call a germline het, *and* if its alt allele fraction is similar to the tumor's, it could be due to a shared artifact.  (For example, even if sample prep and sequencing were completely different, there may be a common alignment error).  Let's model this.  A command line that reveals three relevant instances is:

```java
#!/bin/bash
ref=/humgen/gsa-hpprojects/GATK/bundle/2.8/b37/human_g1k_v37.fasta
tumor=/humgen/gsa-scr1/schandra/cooperjam_MuTect2PASSVariantsAreInNormals/GATK_error/AMUM.post.subset.bam
normal=/humgen/gsa-scr1/schandra/cooperjam_MuTect2PASSVariantsAreInNormals/GATK_error/AMUM.normal.subset.bam
java -jar gatk-protected.jar Mutect2 -R $ref -I $tumor -I $normal -tumor AMUM.post -normal AMUM.normal -L 6:32609886-32610486 -L 7:15725829-15726429 -L 8:75944109-75944709 -O results.vcf
```

**Comment by ldgauthier** [comment]
By "assembly artifact" are you implying that these are "variants" that don't show up in the BWA-aligned BAMs?

**Comment by davidbenjamin** [comment]
@ldgauthier I meant to say "alignment artifact" -- haven't made *that* mistake in a while.  But really the point is that even if sample prep and/or sequencing are different between tumor and normal there is usually *some* common source of artifacts and therefore if the tumor and normal have the same non-diploid allele fraction we should suspect one such artifact.  But, it should be remembered, I have zero actual experience with this.  Does it sound plausible to you?

**Comment by ldgauthier** [comment]
So you're proposing building a probabilistic model to replace the hard filters on the normal LOD and number of alt reads in the normal?

As Takuto has seen in the tumor-only vs. tumor-normal comparison, these sorts of artifacts are quite prevalent (and hard to filter out from tumor-only!)  The tumor-normal modeling is plausible but I was totally at a loss for the tumor-only case.
