### ISSUE TITLE
Use sub-workflows to iterate over single pairs in case CNV/ACNV workflow

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#825]
The current case workflow wdl for CNV/ACNV simply calls a pair workflow multiple times.  Support teams and workbench would prefer to have a single pair workflow that they can run and the GATK dev team can run a WDL that simply runs the pair workflow over a list of pairs.

**Comment by LeeTL1220** [comment]
If you need to populate entity_id from a bam filepath:

``entity_id=sub(sub(p.right.left, "[/]*.*/", ""), "\\.bam$", "")``

This will give the basename.  

This has not been thoroughly tested.

**Comment by LeeTL1220** [comment]
Better version:

``    String entity_id=sub(sub(sub(tumorBam, "gs://",""), "[/]*.*/", ""), "\\.bam$", "")``

**Comment by samuelklee** [comment]
See #988.
