### ISSUE TITLE
Hardcoded paths, which do not exist outside of the Broad, should not be put into json 

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#834]
json accompanying WDL should be viewed as a template.

Both m2 json files contain hardcoded paths that users outside of the Broad (or on the cloud) cannot access.  

I propose using the convention in the CNV json...  Populate parameters that have default values (these would work outside the Broad) and parameters that are needed by the user use ``$__name_of_parameter__``.  This makes these parameters easy to replace in python, using templates (or in bash with sed, etc etc)

**Comment by LeeTL1220** [comment]
Thoughts?  @samuelklee @davidbenjamin @takutosato @asmirnov239 

@vdauwera will need to have these template json files for support of best practice workflows.

**Comment by LeeTL1220** [comment]
Tagging as MuTect2, since those WDLs are in question.

**Comment by takutosato** [comment]
sounds good to me

**Comment by vdauwera** [comment]
:+1:

**Comment by samuelklee** [comment]
Sounds good to me as well.

**Comment by LeeTL1220** [comment]
@takutosato We can put custom wdl in the ``unsupported`` directory.

**Comment by LeeTL1220** [comment]
(or create a new sandbox repo)

**Comment by takutosato** [comment]
I will put the broad in-house wdls in a palantir repo.

**Comment by davidbenjamin** [comment]
Closed by @takutosato in PR #846.
