### ISSUE TITLE
Use gnomAD AFs in M2

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#838]
We use dbSNP essentially to increase the prior probability that an allele is a germline variant.  We could use ExAC in the same way except better because

* it covers the whole exome
* it is more reliable
* it has allele counts data for every variant and thus could be used as a very precise prior in the `AlleleFrequencyCalculator`

**Comment by takutosato** [comment]
Just so you know for tumor only I've been using the version of ExAC minus the TCGA variants: `/humgen/gsa-hpprojects/dev/tsato/resources/ExAC.r0.3.nonTCGA.sites.vep.vcf.gz`

**Comment by LeeTL1220** [comment]
@meganshand 's Tumor-only GATK3 M2 WDL contains this.

**Comment by davidbenjamin** [comment]
@LeeTL1220 This is a little different because it's a prior, not a filter.  This is the right way to do it because it lets us take into account the normal sample likelihoods.  You can extract a lot of useful information from these resources:
* If the site is in ExAC you have a very accurate allele frequency.
* If the site is exonic and *not* in ExAC you get a very low upper bound on allele frequency (i.e. roughly 1 / the size of ExAC) and thus improve sensitivity because you know to be more lenient with the germline filter.
* Ditto on the two points above for the genome resource, although it's less effective since it's smaller.

**Comment by davidbenjamin** [comment]
Upon further thought I am considering getting rid of dbSNP entirely.  1000 Genomes alone, with 2500 samples, has almost as many variants as dbSNP.  gnomAD has 15,000 wgs samples and we would likely miss very little, if anything.

Furthermore, dbSNP has virtually no QC and therefore contains many somatic variants, which is why we need the COSMIC whitelist.  gnomAD is very thoroughly curated (by our friends at the MacArthur lab and the Hail team) and would let us dispense with COSMIC entirely.

@LeeTL1220 @takutosato Thoughts?

**Comment by ldgauthier** [comment]
There was a big kerfuffle about whether gnomAD would contain the TCGA normals or not.  Pretty sure we made two versions, so you probably want the one without.

Otherwise 👍  to replacing dbSNP.

**Comment by davidbenjamin** [comment]
> Pretty sure we made two versions

Wow, good to know.

**Comment by ldgauthier** [comment]
Oops, I was wrong.  ExAC had TCGA, but gnomAD (genomes) doesn't.  v2 might though.  I'll keep an eye on it.

**Comment by davidbenjamin** [comment]
Closed by #1023.
