### ISSUE TITLE
scatter Mutect over pairs and intervals

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#841]
... by creating a single tumor-normal pair workflow that scatters over intervals and calling it as a sub-workflow from a wdl that scatters over pairs.

**Comment by davidbenjamin** [comment]
@takutosato and @LeeTL1220 I should take this one because my fluency in wdl lags behinds yours.  I might ask for help.

**Comment by takutosato** [comment]
@davidbenjamin I already have this working with the NA12878 normal normal eval. I will send you the (not yet PR ready) wdl for your reference.

**Comment by LeeTL1220** [comment]
@takutosato For @meganshand 's information....
