### ISSUE TITLE
The necessity (and difficulty) of learning bias covariates from coverage profiles

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#848]
The new GATK coverage model assumes that the multiplicative bias of the Poisson parameter has the form $\exp(W_{t\mu} z_\mu + m_t)$, where $m_t$ is the average log bias for target $t$ and $W_{t\mu}$, $\mu = 1, ..., D$ are the bias covariates (principal components).

While developing new unit tests with simulated data, we found that the training algorithm has difficulty in inferring the principal components, though, the product $W.z$ is learned correctly. As a consequence, learning $W$ from one dataset and using it for case-sample calling on another dataset (generated using the same model parameters) is unsuccessful. This issue must be investigated. It may be a bug, or a general "poverty of data" problem.

Interestingly, the PoN learned from real (as opposed to simulated) coverage profiles produces decent case-sample calls on another dataset, contrary to simulations. Therefore, there are several possibilities:

1) Mean bias (m) overwhelmingly dominates the contribution from bias principal components in realistic coverage data, such that wrong estimation of principal components does not lead to issues, in which case, why are we taking PCs into account to begin with?!

2) Principal components in realistic coverage data are highly structured, perhaps are sparse in the target space, and perhaps are easier to learn (compare to the dense principal components used in simulations).

We must evaluate both statements using real coverage profiles.

**Comment by mbabadi** [comment]
Issue resolved @samuelklee @davidbenjamin @asmirnov239 it was a bug in simulated data generation code lol :D sorry for keeping you thinking about the wrong problem ;-)

**Comment by samuelklee** [comment]
Phew!  I was thinking about it some more and beginning to question whether I still understood linear algebra.  Glad that it's resolved!
