### ISSUE TITLE
gCNV miscellaneous optimizations and code improvements left from PR review

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#853]
- [ ] thread capping in `SynchronizedUnivariateSolver`
- [ ] faster calculation of prior copy number contribution to log likelihood in `IntegerCopyNumberExpectationsCalculator`
- [ ] optimize `CoverageModelEMWorkspace.replaceMaskedEntries` using Nd4j native ops

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2931](https://github.com/broadinstitute/gatk/issues/2931) via [**ZenHub**](https://www.zenhub.com/)
