### ISSUE TITLE
Mutect2 should report Loss of heterozygosity at germline variant sites

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk-protected#864]
If I remember correctly, Mutect-Classic filtered out sites that had germline calls at them.  This meant it didn't report somatic mutations that involved loss of heterozygosity or new alleles at variant germline sites.  Mutect 2 should report these sites as variant.  

@davidangb Not sure if this already happens, but it seems like a good thing to fix if it doesn't.

**Comment by vdauwera** [comment]
I support this feature request.

**Comment by davidbenjamin** [comment]
@lbergelson LoH is a great idea that we don't do already; we *do* handle new alleles at germline variant sites now.

**Comment by davidbenjamin** [comment]
Actually, I'm having second thoughts.  LoH is a copy-number event that occurs in chunks, so we cold end up emitting (and spending CPU time on) a huge number of additional sites.  Also, @samuelklee is there any reason not to leave the LoH-finding to aCNV?

**Comment by davidbenjamin** [comment]
Yeah, LoH is aCNV's job.  Mutect would do the same thing at much greater expense and with less power.

**Comment by lbergelson** [comment]
@davidbenjamin, aCNV won't detect point mutations leading to LOH at specific sites.  It's an admittedly rare case, and maybe not clinically relevant since reversion to the reference is probably not disease causing, but it means missing real somatic variants.

**Comment by davidbenjamin** [comment]
@lbergelson Ah, I see your point.  Then it becomes an interesting trade-off of time vs sensitivity.  I suppose we could make it optional.  I'll re-open.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2934](https://github.com/broadinstitute/gatk/issues/2934) via [**ZenHub**](https://www.zenhub.com/)
