### ISSUE TITLE
gatk3-style strand artifact filter doesn't work

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/gatk-protected#869]
or at least does not reproduce the behavior in gatk3. After a brief inspection, it looks as though the tumor lod (both strand-aware and strand-agnostic) are about an order of magnitude higher in gatk4 than in gatk3. I suspect the filter never gets triggered because the inflated tumor lod never falls under the filter threshold of 2. 

Although we will soon update the strand artifact filter with our own, we should definitely investigate this because the bug seems to be in the way we calculate tumor lod.

**Comment by takutosato** [comment]
@davidbenjamin

**Comment by takutosato** [comment]
#876

**Comment by davidbenjamin** [comment]
Closed by @takutosato in PR #876.
