### ISSUE TITLE
GC Correction does not do much of a fitting when target sizes are too large

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#870]
There are many possible solutions.  One would be to break the GC adjustment into smaller bins and weight the read count on those bins rather than making an adjustment per target.

In theory, this could happen when we have large exome targets as well, though this is probably seen most in WGS.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2935](https://github.com/broadinstitute/gatk/issues/2935) via [**ZenHub**](https://www.zenhub.com/)
