### ISSUE TITLE
MuTect2 should annotate DP in FORMAT  field

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk-protected#872]
### Tool(s) involved
MuTect2

### Description
Right now, MuTect2 only outputs AD. Users would find it helpful to have the filtered depth like DP in HaplotypeCaller output.

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/gatk/discussion/comment/35778#Comment_35778

**Comment by davidbenjamin** [comment]
@chandrans We suspect that we fixed this somewhere along the line.  @takutosato will check and fix if necessary.

**Comment by takutosato** [comment]
In gatk4 we report both DP and AD.

**Comment by chandrans** [comment]
Great, thanks!
