### ISSUE TITLE
gatk-launch fails after ./gradlew clean shadowJar

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk-protected#873]
This is because the name for the shadow jar differs between public vs. protected, and `gatk-launch` looks for the name used in public. We should just have protected use the suffix `local.jar` like in public.

**Comment by vdauwera** [comment]
What's the target for building the spark jar, `sparkJar` like for `gatk`?

**Comment by droazen** [comment]
Yes, `sparkJar`. Just need to add a `localJar` target, and adjust the name of the created jar, to fix this issue.

**Comment by vdauwera** [comment]
OK I should have just tried before asking; it works :)

And gatk-launch uses it correctly too, for the record.
