### ISSUE TITLE
CRSP specificity validation

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#877]
The CRSP validation takes a set of NA12878 replicate exomes and runs Mutect in tumor-normal mode on every (ordered) pair.  We should create a wdl pipeline that takes in an arbitrary set of replicates.  The specs are:

*Input: list of replicate bams and intervals
*Run Mutect on all pairs
*Calculate false positive rate for SNPs and indels, defined as number of filtered calls per megabase of given intervals
*Report FPR for each pair and the average.

This is all that CRSP autoval does, although it might also be nice to improve upon it by binning false positive by allele fraction.

**Comment by davidbenjamin** [comment]
Note that @takutosato has already done most of the work for this.

**Comment by takutosato** [comment]
- [ ] Edit CountFalsePositives.java to report FPR
- [ ] Update and generalize WDL

**Comment by davidbenjamin** [comment]
Closed by @takutosato in PR #895.
