### ISSUE TITLE
Mutect2 PoN creation

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#881]
Make sure we can do this!

**Comment by davidbenjamin** [comment]
I believe that this was previously done using `CombineVariants`, but I don't see that in gatk 4.  The docs for `MergeVcfs` and `GatherVcfs` say that they only work when all input vcfs have the same sample list, whereas to make a Mutect PoN we call different samples independently and then merge.

@knoblett, @chandrans any thoughts?

**Comment by chandrans** [comment]
Are you saying CombineVariants is not in GATK4 and never will be? If MergeVcfs or GatherVcfs can have option to take in different samples and work like CombineVariants, that would be perfect. For the WDL part, Kate or Soo Hee may have better thoughts

**Comment by davidbenjamin** [comment]
Note to self, @takutosato, and @LeeTL1220: whoever gets to this first takes it.

David has to finish #831, #878, #880, and #885
Takuto has to finish #795, #872, #877, and #882
Lee has to finish #879 and #884

@chandrans we decided that whoever ends up doing this will consult the engine team.

**Comment by davidbenjamin** [comment]
Actually, FYI everybody, this deserves its own CLI.  While replicating the old behavior can be done with `CombineVariants`, we plan on going beyond that.

**Comment by davidbenjamin** [comment]
Closed by #913
