### ISSUE TITLE
Run Mutect WDL as part of Travis build

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#884]
Just like we do for ACNV.

**Comment by LeeTL1220** [comment]
Blocked until the next version of cromwell.

**Comment by LeeTL1220** [comment]
- ``mutect2-replicate-validation.wdl``
- ``mutect2_multi_sample.wdl``
- ``mutect2.wdl``

And the corresponding templates should be used for each.

**Comment by LeeTL1220** [comment]
If this is complete, please close issue #915

**Comment by LeeTL1220** [comment]
Waiting on #916

**Comment by davidbenjamin** [comment]
> If this is complete, please close issue #915 (shouldn't be needed if this one addresses mutect2-replicate-validation.wdl).

@LeeTL1220 does this affect me or Takuto or was it a note to self?

**Comment by davidbenjamin** [comment]
Closed by #949.
