### ISSUE TITLE
Simpler and faster allele fraction likelihoods for HMM segmentation

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#887]
The initial implementation of joint segmentation is prohibitively slow, in part because the allele likelihoods model is expensive.  For segmentation we can very likely get away with a much faster binomial + outlier, or maybe beta-binomial + outlier model.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2937](https://github.com/broadinstitute/gatk/issues/2937) via [**ZenHub**](https://www.zenhub.com/)
