### ISSUE TITLE
Use conditionals to reduce the coverage collection to one task call in case and pon GATK ACNV wdl

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#899]

**Comment by LeeTL1220** [comment]
``CalculateTargetCoverage`` and ``WholeGenomeCoverage`` can be called using a conditional.  The current WDL was a workaround, since it pre-dates cromwell conditionals.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2940](https://github.com/broadinstitute/gatk/issues/2940) via [**ZenHub**](https://www.zenhub.com/)
