### ISSUE TITLE
Basic testing of mutect2-replicate-validation.wdl still incomplete

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#915]
This will be obviated by #884 anyway, but in case that takes a while to deliver.

The testing was slowed by https://github.com/broadinstitute/cromwell/issues/2011

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2948](https://github.com/broadinstitute/gatk/issues/2948) via [**ZenHub**](https://www.zenhub.com/)
