### ISSUE TITLE
Update MuTect2 documentation about not computing obvious germline variants

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk-protected#920]
See [this dsde-docs issue](https://github.com/broadinstitute/dsde-docs/issues/1748#issuecomment-281758111).

I don't have permissions in the repo to assign tickets or change issue labels. This should be assigned to @vdauwera and labeled "docs".

**Comment by vdauwera** [comment]
Port https://github.com/broadinstitute/gsa-unstable/issues/1560 when done.

**Comment by ronlevine** [comment]
Closing since redundant with https://github.com/broadinstitute/gatk-protected/issues/944
