### ISSUE TITLE
Use linkage disequilibrium for tumor-only mode

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#927]
In tumor-only mode we can use correlations among variants to impute germline variants.

**Comment by mbabadi** [comment]
I thought about doing this a while ago for germline Het SNP calling from tumor-only data, but I kept hearing that LD is lost in tumor samples, though I'm not quite convinced... I'd like to brainstorm on this.

**Comment by davidbenjamin** [comment]
I'm not quite convinced either.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2950](https://github.com/broadinstitute/gatk/issues/2950) via [**ZenHub**](https://www.zenhub.com/)
