### ISSUE TITLE
Make ordering of contigs in ReadCountCollection and AllelicCountCollection consistent.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#933]
This inconsistency gave rise to a bug in joint segmentation.  I think it ultimately stems from the fact that the common SNP list used to generate pulldowns is not sorted in lexicographical order.

**Comment by davidbenjamin** [comment]
Note: see broadinstitute/gatk#1754.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2951](https://github.com/broadinstitute/gatk/issues/2951) via [**ZenHub**](https://www.zenhub.com/)
