### ISSUE TITLE
The M2 WDL task for ProcessOptionalArguments can use a smaller docker image.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#937]
By grabbing the gatk-protected docker image (or whichever is being used for M2), this task commits to a ~2GB download.  However, the task does basic bash commands, which could easily be performed using one of the ``ubuntu:14.04`` images or maybe even one smaller.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2952](https://github.com/broadinstitute/gatk/issues/2952) via [**ZenHub**](https://www.zenhub.com/)
