### ISSUE TITLE
gatk-protected should tag releases using annotated tags rather than unannotated tags.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk-protected#940]
Since using unannotated tags causes a straightforward `git describe` to fail.

**Comment by lbergelson** [comment]
we should sign them too...

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2953](https://github.com/broadinstitute/gatk/issues/2953) via [**ZenHub**](https://www.zenhub.com/)
