### ISSUE TITLE
More M2 normal-normals

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#958]
We currently have an ICE exome normal-normal analysis set up i.e. you can `cd` into `/dsde/working/davidben/mutect/validations/normalNormal` and `/Users/home/davidben/cromwell/run_sge.sh normal_normal.wdl normal_normal.json` is all you need to get the analysis.

Let's set this up for a few other replicate sets, which we can grab from the Palantir wiki.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2961](https://github.com/broadinstitute/gatk/issues/2961) via [**ZenHub**](https://www.zenhub.com/)
