### ISSUE TITLE
Clean up Mutect2.wdl

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/gatk-protected#959]
Mutect2.wdl is a monolithic beast that does way more than what it's designed to do i.e. run Mutect2. It's good style to split standalone tasks (Mutect2, Oncotator, OxoG filter) into modules. On the other hand, in the cloud it's cheaper to have all tasks in one wdl. We should find a good balance between these opposing forces.

**Comment by davidbenjamin** [comment]
@takutosato I recently made a few modest (and orthogonal) steps to clean the wdl (PR #974).  Let me know if the rebase gets messy, since it will be my fault for causing the mess.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2962](https://github.com/broadinstitute/gatk/issues/2962) via [**ZenHub**](https://www.zenhub.com/)
