### ISSUE TITLE
Three M2 FPs

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk-protected#960]
When I developed the MuTect2 hands-on tutorial for the Belgium workshop, I picked a number of indel calls for manual review. A number of these look like bugs. I've been asked to share these so do with them what you will.

- For context on the data, see the tutorial worksheet. Basically, I use a WES Tumor/Normal sample pair, align to GRCh38 and call mutations using v3.7 MuTect2 and a PoN (I derive this from 40 1KG samples).
    - If you have questions on the background, comment on the Google doc: <https://docs.google.com/a/broadinstitute.org/document/d/1T6ujDc28fWXJEoyenIPVi7pOCte4c2JnX5rSvm30UEQ/edit?usp=sharing>
    - To print the tutorial worksheet, here's the static PDF: <https://drive.google.com/open?id=0BzI1CyccGsZickI3M3lJWUk5TjQ>
- Data bundle: <https://drive.google.com/open?id=0BzI1CyccGsZidVduaEhhMk9TZE0>
- Synopsis on ten interesting sites that we showcase to tutorial attendees: <https://docs.google.com/a/broadinstitute.org/spreadsheets/d/16NjxfZdtBz6nkZw-3Q_7gdGRwreecksMCH8hgnGUJx0/edit?usp=sharing>. In some of these, we see M2 detects  structural variants, albeit as an indel.

I have three additional sites that, after review by two pairs of eyes, we decided could be bugs.

---
## Likely bugs in M2/HC
All of these sites PASS.
```
chr7	100958232	.	C	CGAGACCACATCCCACAGTACTCCCAGCTTCACTTCTTCAATCAGCACCACT	.	PASS	ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=10.60;TLOD=6.33	GT:AD:AF:ALT_F1R2:ALT_F2R1:QSS:REF_F1R2:REF_F2R1	0/0:229,0:0.069:0:0:6697,0:99:130	0/1:143,0:0.042:0:0:4084,0:60:83	-	bamout is missing reads in this region.
chr14	81108484	.	C	CT	.	PASS	ECNT=1;HCNT=27;MAX_ED=.;MIN_ED=.;NLOD=9.65;RPA=9,10;RU=T;STR;TLOD=25.63	GT:AD:AF:ALT_F1R2:ALT_F2R1:QSS:REF_F1R2:REF_F2R1	0/0:34,0:0.00:0:0:939,0:18:16	0/1:0,36:1.00:20:16:0,1052:0:0	LOH; the most interesting site	Actually, this looks like a sequencing artifact to me -- polymerase slippage is very common in poly-A regions
chrX	132097402	.	TACACAC	T	.	PASS	ECNT=1;HCNT=2;MAX_ED=.;MIN_ED=.;NLOD=2.82;RPA=13,10;RU=AC;STR;TLOD=6.60	GT:AD:AF:ALT_F1R2:ALT_F2R1:QSS:REF_F1R2:REF_F2R1	0/0:30,5:0.00:0:0:376,0:7:7	0/1:32,4:0.080:1:1:610,59:9:12	tricky; looks like should have been filtered?	This looks like a HC/M2 bug
```

1. Bamout is missing reads in this region despite it having been called.
2. I thought an LOH. Julian says it looks like a sequencing artifact in a poly-A region.
3. This is a tricky site where it looks like it should have been filtered but was not. Julian says it looks like a HC/M2 bug.

**Comment by sooheelee** [comment]
@davidbenjamin Here you go. I hope I posted to the right repo. I don't have permissions to assign you so I'm just pinging you.

**Comment by sooheelee** [comment]
Ah, and in lieu of screenshots, I thought I'd let you load the provided data into IGV and view yourselves. No need for you to process anything. All the data is in the provided bundle.

**Comment by davidbenjamin** [comment]
@soohee Thanks!  We'll have to see what GATK 4 does with these sites.

**Comment by sooheelee** [comment]
If GATK4 improves the calling, then let me know. I want to download a version of the tool to use going forward.

**Comment by davidbenjamin** [comment]
@sooheelee GATK 4 correctly filters the chr7 site, still has a false positive on chr14, and doesn't call the chrX site at all.  So 2/3 are fixed.

The remaining false positive on chr14 looks obvious wrong because the reads, in both the original alignment and the bamout, have more bases that disagree with the reference than agree.

**Comment by davidbenjamin** [comment]
The chr14 site looks like a Plain Old Artifact to me.  There's no single smoking gun except for the very high AF.  We will hopefully be able to fix things like this when we have a proper machine learning PoN.
