### ISSUE TITLE
GATK CNV/ACNV automated WDL tests should use docker

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#961]

**Comment by LeeTL1220** [comment]
Currently, the tests do not use docker.  The M2 WDL does use docker.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2963](https://github.com/broadinstitute/gatk/issues/2963) via [**ZenHub**](https://www.zenhub.com/)
