### ISSUE TITLE
Refactor WGS and WES coverage collection to be more analogous.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#975]
Should be an equivalent of PadTargets for WGS that outputs a file specifying the bins.  Alternatively, the WES coverage collection CLI should calculate padded targets on the fly.  This will simplify the WDL and reduce the number of tasks.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2964](https://github.com/broadinstitute/gatk/issues/2964) via [**ZenHub**](https://www.zenhub.com/)
