### ISSUE TITLE
Mutect WDL requires intervals even for wgs

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#979]
The `SplitIntervals` task does not know to split the whole genome if no intervals are provided, and therefore the whole workflow requires intervals.  This is a nuisance for wgs.

**Comment by sooheelee** [comment]
Picard ScatterIntervalsByNs can split an entire genome into an interval_list for you. It's fairly fast. For GRCh38's primary assembly, it took 1.23 minutes on my laptop.

**Comment by davidbenjamin** [comment]
Closed by PR #1010.
