### ISSUE TITLE
CollectAllelicCounts should extend LocusWalker

### ISSUE THREAD

**Issue by asmirnov239** [broadinstitute/gatk-protected#987]
Replace the `AllelicCountCollector` with the implementation using LocusWalker

**Comment by LeeTL1220** [comment]
Actually, I have to replace ``CollectAllelicCounts`` and ``AllelicCountCollector``

**Comment by LeeTL1220** [comment]
Dependent on: 

https://github.com/broadinstitute/gatk/pull/2661

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2968](https://github.com/broadinstitute/gatk/issues/2968) via [**ZenHub**](https://www.zenhub.com/)
