### ISSUE TITLE
Allow CollectSequencingArtifactMetrics to be skipped if user specifies an input file for the Orientation Bias filter.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#989]
In other words, if a user specifies the file to use, do not run the task.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2970](https://github.com/broadinstitute/gatk/issues/2970) via [**ZenHub**](https://www.zenhub.com/)
