### ISSUE TITLE
Make RobustBrentSolver more flexible

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk-protected#990]
`RobustBrentSolver` is a univariate solver developed as a part of GATK coverage model. It has a Brent solver at the core but tries to avoid spurious non-bracketing conditions by creating a collection of refined sub-brackets.

The implementation needs to be made more flexible:
- Allow the user to specify how sub-brackets are generated. The default grid is a logarithmic grid concentrated about the leftmost endpoint followed by uniform refinement of each grid element.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2971](https://github.com/broadinstitute/gatk/issues/2971) via [**ZenHub**](https://www.zenhub.com/)
