### ISSUE TITLE
Simulate tumors using haploid samples

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#995]
We have a Q script for in silico mixing, which we should port to wdl, and we have haploid exomes and genomes.  We should use this to make great truth data for testing Mutect.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2974](https://github.com/broadinstitute/gatk/issues/2974) via [**ZenHub**](https://www.zenhub.com/)
