### ISSUE TITLE
Speed up M2 on bad regions

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#997]
Mutect 2 spends a disproportionate amount of time in certain nasty regions.  For example, on average a 500,000 bp chunk of DREAM challenge 3 usually takes 30 seconds on a single core, but in some cases takes hours.  This is very bad both for scattered jobs and total single-core run time.

These bad regions are characterized by large numbers of false positives with bad mapping quality and very large normal artifact lods.  The depth is often high due to mapping issues, which aggravates the problem.  We should be able to modify our active region determination so that these bad sites don't trigger the assembly and likelihoods engines.

**Comment by ldgauthier** [comment]
Have you localized the regions yet?  Dave Shiga did some work for us on
slow regions that we causing problems for GenotypeGVCFs in production (not
quite apples to apples) and he found that the centromeres cause a lot of
problems and our MPG collaborators don't trust calls there anyway.  In
production for HaplotypeCaller we use an interval list for genomes too
(/seq/references/Homo_sapiens_assembly19/v1/variant_calling/wgs_calling_regions.v1.interval_list)
to avoid centromeres, telomeres, and gaps in the reference.

That is to say, don't waste too much effort optimizing regions where we
won't trust any calls anyway.

**Comment by LeeTL1220** [comment]
We should leverage that list for CNV tools as well.  We get a lot of false positive CNVs in centromeres (particularly chr9).

**Comment by davidbenjamin** [comment]
@ldgauthier Thank you!  I have localized the regions, and that HaplotypeCaller interval list seems to exclude most or all of them (I can't say for sure because I have only localized down to about 100 kb).  In our DREAM challenge wgs benchmarks we will lose about one in ten thousand true positives, which I can easily live with.

This will save us a lot of time.

**Comment by davidbenjamin** [comment]
@samuelklee if you're not already aware of this wgs intervals whitelist.

**Comment by samuelklee** [comment]
Excellent, thanks.  Looping in @asmirnov239, @mbabadi, and @achevali.

**Comment by samuelklee** [comment]
Looping in @danielrosebrock and @dlivitz as well.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2975](https://github.com/broadinstitute/gatk/issues/2975) via [**ZenHub**](https://www.zenhub.com/)
